/* Floating detail uses a fixed overlay: hover and keyboard focus never resize Calendar cells. */
(()=>{
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function legs(t){return t.type==='flight'?HVJourney.flightLegs(t):HVJourney.groundLegs(t);}
 function transport(t){const items=legs(t);return `<strong class="transport-route-heading">${HVTransportIcons.html(t.type)} ${E(HVJourneys.transportLabel(t))}</strong><div class="journey-leg-details">${items.map((l,i)=>`<div>${items.length>1?'<strong>Leg '+(i+1)+' · '+E(HVJourney.transportLabel({...l,type:t.type}))+'</strong>':''}${t.type==='flight'?`<small>${E(HVJourney.airportDetails(l.start,HVJourneys.airportFor))} → ${E(HVJourney.airportDetails(l.end,HVJourneys.airportFor))}</small>`:''}<small>${E([l.airline?.name,l.flightNumber,l.operator||t.operator,l.serviceNumber||t.serviceNumber].filter(Boolean).join(' · '))}</small><small>${E(l.startLocal?.replace('T',' ')||'Time not recorded')} → ${E(l.endLocal?.replace('T',' ')||'Time not recorded')}${(l.start?.timeZone||l.start?.timezone)?' · Departure '+E(l.start.timeZone||l.start.timezone):''}${(l.end?.timeZone||l.end?.timezone)?' · Arrival '+E(l.end.timeZone||l.end.timezone):''}</small></div>`).join('')}</div>${t.bookingReference?'<p>Booking: '+E(t.bookingReference)+'</p>':''}${t.seat?'<p>Seat: '+E(t.seat)+'</p>':''}${t.notes?'<p class="trip-notes">'+E(t.notes)+'</p>':''}${HVPrices.detail(t)}`;}
 let tip,active,hoverFrame,pinnedCountryList=false;
 function hide(){cancelAnimationFrame(hoverFrame);hoverFrame=null;pinnedCountryList=false;tip?.remove();tip=null;if(active){active.removeAttribute('aria-describedby');active=null;}}
 function show(b){if(!b||b===active)return;hide();let content='';if(b.matches('[data-calendar-edit-country]')){const s=state.stays.find(s=>s.id===b.dataset.calendarEditCountry);if(s)content=`<strong>${E(s.countryName)}</strong>${s.location?'<p>'+E(s.location)+'</p>':''}${SCHENGEN.has(s.countryCode)?'<p>Schengen Area</p>':''}`;}else if(b.matches('[data-calendar-more-countries]')){const ids=JSON.parse(b.dataset.calendarMoreCountries),byId=new Map(state.stays.map(s=>[s.id,s])),extra=ids.map(id=>byId.get(id)).filter(Boolean);if(extra.length)content='<strong>Additional countries</strong><ul class="calendar-extra-country-list">'+extra.map(s=>'<li>'+flagHtml(s.domesticDestination||s.countryCode,'calendar-chip-flag')+'<span>'+E(s.countryName)+'</span></li>').join('')+'</ul>';}else if(b.matches('.calendar-day-transport')){const t=state.transports.find(t=>t.id===b.dataset.calendarEditTransport);if(t)content=transport(t);}else if(b.matches('.calendar-lodging-half')){const a=state.accommodations.find(a=>a.id===b.dataset.calendarEditAccommodation);if(a)content=`<strong>${E(a.propertyName)}</strong><p>${E(a.checkIn)} ${E(a.checkInTime)} → ${E(a.checkOut)} ${E(a.checkOutTime)}</p><p>${E(HVAddress.address(a.place)||HVAddress.text(a.location))}</p>${HVPrices.detail(a)}${a.notes?'<p class="trip-notes">'+E(a.notes)+'</p>':''}`;}if(!content)return;active=b;tip=document.createElement('div');tip.id='calendarFloatingDetail';tip.className='calendar-floating-detail';tip.setAttribute('role','tooltip');if(b.matches('[data-calendar-more-countries]'))tip.classList.add('calendar-extra-countries-detail');tip.innerHTML=content;document.body.append(tip);b.setAttribute('aria-describedby',tip.id);const box=b.getBoundingClientRect(),rect=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-rect.width-8,box.left))+'px';tip.style.top=(box.bottom+rect.height+8<innerHeight?box.bottom+6:Math.max(8,box.top-rect.height-6))+'px';}
 const selector='#calendar [data-calendar-edit-country],#calendar [data-calendar-more-countries],.calendar-day-transport,.calendar-lodging-half';
 const insideCountryList=node=>active?.matches('[data-calendar-more-countries]')&&tip?.contains(node);
 document.addEventListener('mouseover',e=>{const b=e.target.closest(selector);cancelAnimationFrame(hoverFrame);if(b)hoverFrame=requestAnimationFrame(()=>{hoverFrame=null;if(b.isConnected&&b.matches(':hover'))show(b);});});
 document.addEventListener('pointermove',e=>{const b=e.target.closest(selector);if(b)show(b);else if(!pinnedCountryList&&!insideCountryList(e.target))hide();});
 document.addEventListener('mouseout',e=>{if(!pinnedCountryList&&e.target.closest(selector)&&!e.relatedTarget?.closest(selector)&&!insideCountryList(e.relatedTarget))hide();});
 document.addEventListener('focusin',e=>show(e.target.closest(selector)));document.addEventListener('focusout',hide);
 document.addEventListener('click',e=>{const b=e.target.closest('#calendar [data-calendar-more-countries]');if(b){e.preventDefault();e.stopPropagation();show(b);pinnedCountryList=true;}else if(!insideCountryList(e.target))hide();},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(active?.matches('[data-calendar-more-countries]')){e.preventDefault();e.stopImmediatePropagation();}hide();}});window.addEventListener('scroll',e=>{if(!insideCountryList(e.target))hide();},true);window.addEventListener('resize',hide);window.addEventListener('hv-calendar-rendered',hide);
 window.HVCalendarDetails={transport,hide};
})();
