/* Private catalogue; historical records always retain their own place snapshot. */
(() => {
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function migrate(rows,save=true){rows||=(state.savedPlaces||=[]);const before=rows.length;const records=[...(state.accommodations||[]).map(r=>({p:r.place,profileId:r.profileId})),...(state.placeVisits||[]).map(r=>({p:r.place,profileId:r.profileId})),...(state.transports||[]).flatMap(r=>(r.type==='flight'?HVJourney.flightLegs(r):[r]).flatMap(l=>[l.start,l.end].map(p=>({p,profileId:r.profileId}))))];for(const {p,profileId}of records)if(p&&(p.manualAirport||String(p.id||'').startsWith('manual:')))HVSavedModel.upsert(rows,p,profileId);if(save&&rows.length!==before)persist();return rows;}
 function save(p,profileId=state.activeProfileId){migrate();const row=HVSavedModel.upsert(state.savedPlaces,p,profileId);delete row.deleted;row.place.aliases=[...new Set([...(row.place.aliases||[]),...(p.aliases||[]),row.place.name,p.name].filter(Boolean))];row.sourceIds=[...new Set([...(row.sourceIds||[]),p.id].filter(Boolean))];for(const [key,value]of Object.entries(p))if((row.place[key]==null||row.place[key]==='')&&value!=null&&value!=='')row.place[key]=JSON.parse(JSON.stringify(value));persist();return {...p,savedPlaceId:row.id};}
 function search(term){
   const rows=migrate(JSON.parse(JSON.stringify(state.savedPlaces||[])),false);
   const historical=HVAccommodationPlaces.groups(HVJourney.scoped(state.accommodations||[],state.activeProfileId));
   for(const group of historical){if(rows.some(r=>r.deleted&&(!r.profileId||state.activeProfileId==='all'||r.profileId===state.activeProfileId)&&(HVAccommodationPlaces.same(r.place,group.place)||group.records.some(a=>a.place?.id&&(r.place.id===a.place.id||r.sourceIds?.includes(a.place.id))))))continue;const saved=rows.find(r=>!r.deleted&&(!r.profileId||state.activeProfileId==='all'||r.profileId===state.activeProfileId)&&HVAccommodationPlaces.same(r.place,group.place));if(saved){const i=rows.indexOf(saved);rows[i]={...saved,place:{...saved.place,aliases:[...new Set([...(saved.place.aliases||[]),...group.aliases])]}};}else rows.push({id:group.place.savedPlaceId||'historical:'+group.records[0].id,profileId:group.records[0].profileId,place:group.place});}
   return HVSavedModel.search(rows,term,state.activeProfileId).map(p=>({...HVAddress.place(p),...(String(p.savedPlaceId).startsWith('historical:')?{savedPlaceId:undefined}:{} )}));
 }
 function manage(){migrate();const d=document.createElement('dialog');d.className='place-search-dialog';d.setAttribute('aria-label','Saved places');d.innerHTML='<div class="place-search-form"><div class="dialog-head"><h2>Saved places</h2><button type="button" class="text-btn" data-close>Close ×</button></div><p>Your private reusable places. Editing or removing these keeps historical journey details intact.</p><input type="search" placeholder="Search saved places" aria-label="Search saved places"><div data-saved-list></div><button class="secondary" type="button" data-add>Add a place</button></div>';
 document.body.append(d);const list=d.querySelector('[data-saved-list]');function render(){const query=d.querySelector('input').value,rows=HVJourney.scoped(state.savedPlaces,state.activeProfileId).filter(r=>!r.deleted).filter(r=>!query||HVSavedModel.search([r],query,state.activeProfileId).length);list.innerHTML=rows.map(r=>`<article class="saved-place-row"><strong>${E(HVAddress.field(r.place,'name'))}</strong><p>${E([r.place.type,HVAddress.address(r.place),HVAddress.field(r.place,'city')||HVAddress.field(r.place,'area'),HVAddress.field(r.place,'countryName'),r.place.iata,r.place.icao].filter(Boolean).join(' · '))}</p><button class="text-btn" data-edit="${E(r.id)}">Edit</button><button class="text-btn" data-delete="${E(r.id)}">Remove from saved places</button><label class="field"><span>Merge duplicate into</span><select data-merge="${E(r.id)}"><option value="">Choose the place to keep</option>${rows.filter(x=>x.id!==r.id).map(x=>`<option value="${E(x.id)}">${E(HVAddress.field(x.place,'name'))} · ${E(HVAddress.address(x.place)||HVAddress.field(x.place,'countryName'))}</option>`).join('')}</select></label></article>`).join('')||'<p>No saved places yet.</p>';}
 d.querySelector('input').oninput=render;d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('[data-add]').onclick=()=>HVPlaces.open({onSelect:p=>{save(p);render();}});
 d.onclick=e=>{const edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-delete]');if(edit){const row=state.savedPlaces.find(r=>r.id===edit.dataset.edit);HVPlaces.open({place:row.place,manageSaved:true,onSelect:p=>{row.sourceIds=[...new Set([...(row.sourceIds||[]),row.place.id,p.id].filter(Boolean))];row.place=JSON.parse(JSON.stringify(p));persist();render();}});}if(remove&&confirm('Remove this reusable place? Existing journeys will keep their saved location details.')){state.savedPlaces.find(r=>r.id===remove.dataset.delete).deleted=true;persist();render();}};
 d.onchange=e=>{const select=e.target.closest('[data-merge]');if(!select?.value)return;if(confirm('Keep the selected saved place and remove this duplicate? Historical records will stay unchanged.')){state.savedPlaces.find(r=>r.id===select.dataset.merge).deleted=true;persist();render();}else select.value='';};d.onclose=()=>d.remove();render();d.showModal();}
 window.HVSavedPlaces={save,search,manage,migrate};document.addEventListener('click',e=>{if(e.target.closest('[data-manage-places]'))manage();});
})();
