/* Private catalogue; historical records always retain their own place snapshot. */
(() => {
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function migrate(){state.savedPlaces||=[];const before=state.savedPlaces.length;const records=[...(state.accommodations||[]).map(r=>({p:r.place,profileId:r.profileId})),...(state.placeVisits||[]).map(r=>({p:r.place,profileId:r.profileId})),...(state.transports||[]).flatMap(r=>(r.type==='flight'?HVJourney.flightLegs(r):[r]).flatMap(l=>[l.start,l.end].map(p=>({p,profileId:r.profileId}))))];for(const {p,profileId}of records)if(p&&(p.manualAirport||String(p.id||'').startsWith('manual:')))HVSavedModel.upsert(state.savedPlaces,p,profileId);if(state.savedPlaces.length!==before)persist();}
 function save(p,profileId=state.activeProfileId){migrate();const row=HVSavedModel.upsert(state.savedPlaces,p,profileId);delete row.deleted;row.sourceIds=[...new Set([...(row.sourceIds||[]),p.id].filter(Boolean))];for(const [key,value]of Object.entries(p))if((row.place[key]==null||row.place[key]==='')&&value!=null&&value!=='')row.place[key]=JSON.parse(JSON.stringify(value));persist();return {...p,savedPlaceId:row.id};}
 function search(term){migrate();return HVSavedModel.search(state.savedPlaces,term,state.activeProfileId);}
 function manage(){migrate();const d=document.createElement('dialog');d.className='place-search-dialog';d.setAttribute('aria-label','Saved places');d.innerHTML='<div class="place-search-form"><div class="dialog-head"><h2>Saved places</h2><button type="button" class="text-btn" data-close>Close ×</button></div><p>Your private reusable places. Editing or removing these keeps historical journey details intact.</p><input type="search" placeholder="Search saved places" aria-label="Search saved places"><div data-saved-list></div><button class="secondary" type="button" data-add>Add a place</button></div>';
 document.body.append(d);const list=d.querySelector('[data-saved-list]');function render(){const query=d.querySelector('input').value,rows=HVJourney.scoped(state.savedPlaces,state.activeProfileId).filter(r=>!r.deleted).filter(r=>!query||HVSavedModel.search([r],query,state.activeProfileId).length);list.innerHTML=rows.map(r=>`<article class="saved-place-row"><strong>${E(r.place.name)}</strong><p>${E([r.place.type,r.place.address,r.place.city||r.place.area,r.place.countryName,r.place.iata,r.place.icao,r.place.code].filter(Boolean).join(' · '))}</p><button class="text-btn" data-edit="${E(r.id)}">Edit</button><button class="text-btn" data-delete="${E(r.id)}">Remove from saved places</button><label class="field"><span>Merge duplicate into</span><select data-merge="${E(r.id)}"><option value="">Choose the place to keep</option>${rows.filter(x=>x.id!==r.id).map(x=>`<option value="${E(x.id)}">${E(x.place.name)} · ${E(x.place.address||x.place.countryName)}</option>`).join('')}</select></label></article>`).join('')||'<p>No saved places yet.</p>';}
 d.querySelector('input').oninput=render;d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('[data-add]').onclick=()=>HVPlaces.open({onSelect:p=>{save(p);render();}});
 d.onclick=e=>{const edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-delete]');if(edit){const row=state.savedPlaces.find(r=>r.id===edit.dataset.edit);HVPlaces.open({place:row.place,manageSaved:true,onSelect:p=>{row.sourceIds=[...new Set([...(row.sourceIds||[]),row.place.id,p.id].filter(Boolean))];row.place=JSON.parse(JSON.stringify(p));persist();render();}});}if(remove&&confirm('Remove this reusable place? Existing journeys will keep their saved location details.')){state.savedPlaces.find(r=>r.id===remove.dataset.delete).deleted=true;persist();render();}};
 d.onchange=e=>{const select=e.target.closest('[data-merge]');if(!select?.value)return;if(confirm('Keep the selected saved place and remove this duplicate? Historical records will stay unchanged.')){state.savedPlaces.find(r=>r.id===select.dataset.merge).deleted=true;persist();render();}else select.value='';};d.onclose=()=>d.remove();render();d.showModal();}
 window.HVSavedPlaces={save,search,manage,migrate};document.addEventListener('click',e=>{if(e.target.closest('[data-manage-places]'))manage();});
})();
