/* Herald Voyages travel-specific notes, checklists and trip budgets. */
(() => {
  'use strict';
  const E=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const get=id=>document.getElementById(id)||window.HVPages?.get(id);
  const noteCategories=['General','Itinerary','Accommodation','Transport','Entry requirements','Visa','Health','Money','Packing','Food','Places to visit','Booking information','Contact information','Emergency information','Other'];
  const expenseCategories=['Flights','Accommodation','Trains','Buses','Ferries','Taxis','Car hire','Fuel','Public transport','Food & drink','Activities','Tours','Visas / entry fees','Insurance','Shopping','Other'];
  const paymentStates=['Not booked','Booked','Deposit paid','Part paid','Paid','Refund pending','Refunded'];
  const templates={
    'before-booking':{title:'Before booking',sections:[['Before booking',['Check passport validity','Check visa/entry requirements','Check travel insurance','Check flight options','Check accommodation','Check airport transfers']]]},
    'before-departure':{title:'Before departure',sections:[['Before departure',['Check in for flight','Download boarding passes','Download offline maps','Confirm accommodation','Confirm airport transfer','Check currency/payment options','Check roaming/eSIM','Check weather','Pack medication','Charge power bank']]]},
    documents:{title:'Documents',sections:[['Documents',['Passport','Visa/eVisa','Travel insurance','Flight confirmation','Hotel confirmation','Driving licence','International driving permit if needed','Vaccination certificate where applicable']]]},
    packing:{title:'Packing',sections:[['Essentials',['Passport / travel documents','Wallet / payment cards','Phone and charger','Medication']],['Clothing',['Weather-appropriate layers','Comfortable shoes']],['Useful extras',['Power bank','Travel adaptor','Reusable water bottle']]]},
    blank:{title:'My checklist',sections:[['Checklist',[]]]}
  };
  let noteTripFilter='',budgetTripId='';

  function ensure(){for(const key of ['notes','checklists','budgets','expenses'])if(!Array.isArray(state[key]))state[key]=[];}
  function trip(id){return (state.trips||[]).find(t=>t.id===id);}
  function tripLabel(id){return trip(id)?.name||'Standalone travel';}
  function tripOptions(selected='',allLabel='All travel'){return '<option value="">'+E(allLabel)+'</option>'+HVJourney.scoped(state.trips||[],state.activeProfileId).map(t=>'<option value="'+E(t.id)+'" '+(t.id===selected?'selected':'')+'>'+E(t.name||'Untitled trip')+'</option>').join('');}
  function formatDate(value){if(!value)return'';try{return new Date(value+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});}catch{return value;}}
  function inline(text){return E(text).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');}
  function noteBody(text=''){
    const lines=String(text).split(/\r?\n/),out=[];let list=null;
    const close=()=>{if(list){out.push('</'+list+'>');list=null;}};
    for(const raw of lines){const bullet=raw.match(/^\s*[-*]\s+(.+)/),number=raw.match(/^\s*\d+[.)]\s+(.+)/);if(bullet||number){const type=bullet?'ul':'ol';if(list!==type){close();list=type;out.push('<'+type+'>');}out.push('<li>'+inline((bullet||number)[1])+'</li>');continue;}close();if(raw.trim())out.push('<p>'+inline(raw)+'</p>');}
    close();return out.join('');
  }
  function relatedOptions(tripId,selected=''){
    const rows=[];
    for(const a of state.accommodations||[])if(!tripId||a.tripId===tripId)rows.push(['accommodation:'+a.id,'Hotel · '+(a.propertyName||a.location||'Accommodation')]);
    for(const t of state.transports||[])if(!tripId||t.tripId===tripId)rows.push(['transport:'+t.id,(HVJourney.types[t.type]||t.type)+' · '+HVJourney.transportLabel(t,window.HVJourneys?.airportFor)]);
    for(const s of state.stays||[])if(!tripId||s.tripId===tripId)rows.push(['country:'+s.id,'Country · '+(s.countryName||s.countryCode)]);
    for(const p of state.placeVisits||[])if((!tripId||p.tripId===tripId)&&p.category==='locations')rows.push(['location:'+p.id,'Place · '+(p.place?.name||'Saved location')]);
    return '<option value="">No specific item</option>'+rows.map(([value,label])=>'<option value="'+E(value)+'" '+(value===selected?'selected':'')+'>'+E(label)+'</option>').join('');
  }
  function relationLabel(note){if(!note.relatedType||!note.relatedId)return'';const key=note.relatedType+':'+note.relatedId,html=relatedOptions(note.tripId,key),holder=document.createElement('select');holder.innerHTML=html;return holder.selectedOptions[0]?.textContent||'';}
  function formatInsert(textarea,kind){
    const start=textarea.selectionStart,end=textarea.selectionEnd,chosen=textarea.value.slice(start,end),before=textarea.value.slice(0,start),after=textarea.value.slice(end);let insert='';
    if(kind==='bold')insert='**'+(chosen||'text')+'**';
    if(kind==='bullet')insert=(chosen||'item').split(/\n/).map(x=>'- '+x.replace(/^[-*]\s*/,'')).join('\n');
    if(kind==='number')insert=(chosen||'item').split(/\n/).map((x,i)=>(i+1)+'. '+x.replace(/^\d+[.)]\s*/,'' )).join('\n');
    if(kind==='link')insert='['+(chosen||'link text')+'](https://)';
    textarea.value=before+insert+after;textarea.focus();textarea.setSelectionRange(start,start+insert.length);
  }
  function persistAnd(render){persist();render?.();}

  function openNote(existing){
    const note=existing||{},dialog=document.createElement('dialog');dialog.className='dialog travel-tool-dialog';dialog.setAttribute('aria-label',existing?'Edit travel note':'New travel note');
    const relation=[note.relatedType,note.relatedId].filter(Boolean).join(':');
    dialog.innerHTML=`<form class="dialog-card travel-note-form"><div class="dialog-head"><div><p class="eyebrow">TRAVEL NOTE</p><h2>${existing?'Edit note':'New note'}</h2></div><button type="button" class="icon-btn" data-close>×</button></div>
      <label class="field"><span>Title</span><input name="title" maxlength="120" required value="${E(note.title)}"></label>
      <div class="form-grid"><label class="field"><span>Trip <em>optional</em></span><select name="tripId">${tripOptions(note.tripId||noteTripFilter,'Across all travel')}</select></label><label class="field"><span>Date <em>optional</em></span><input name="date" type="date" value="${E(note.date)}"></label></div>
      <div class="form-grid"><label class="field"><span>Category <em>optional</em></span><select name="category"><option value="">No category</option>${noteCategories.map(c=>'<option '+(c===note.category?'selected':'')+'>'+E(c)+'</option>').join('')}</select></label><label class="field"><span>Related travel item <em>optional</em></span><select name="related">${relatedOptions(note.tripId||noteTripFilter,relation)}</select></label></div>
      <div class="note-format-bar" role="toolbar" aria-label="Note formatting"><button type="button" data-format="bold"><strong>B</strong></button><button type="button" data-format="bullet">• List</button><button type="button" data-format="number">1. List</button><button type="button" data-format="link">Link</button></div>
      <label class="field"><span>Note</span><textarea name="body" rows="10" maxlength="20000" placeholder="Booking details, local contact, places to remember…">${E(note.body)}</textarea></label>
      <label class="check-row compact-check"><input type="checkbox" name="pinned" ${note.pinned?'checked':''}><span><strong>Pin this note</strong><small>Keep important information at the top.</small></span></label>
      <p class="form-error" role="alert"></p><div class="dialog-actions">${existing?'<button type="button" class="danger-link" data-delete>Delete note</button>':''}<div class="spacer"></div><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save note</button></div></form>`;
    document.body.append(dialog);const form=dialog.querySelector('form');
    form.elements.tripId.onchange=()=>{form.elements.related.innerHTML=relatedOptions(form.elements.tripId.value,form.elements.related.value);};
    dialog.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>formatInsert(form.elements.body,b.dataset.format));
    dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());
    dialog.querySelector('[data-delete]')?.addEventListener('click',()=>{if(confirm('Delete this travel note?')){state.notes=state.notes.filter(n=>n.id!==note.id);persistAnd(renderNotesTool);dialog.close();}});
    form.onsubmit=e=>{e.preventDefault();const related=form.elements.related.value.split(':'),record={...note,id:note.id||uid(),profileId:note.profileId??state.activeProfileId,title:form.elements.title.value.trim(),body:form.elements.body.value.trim(),tripId:form.elements.tripId.value||null,date:form.elements.date.value||null,category:form.elements.category.value||null,pinned:form.elements.pinned.checked,relatedType:related[0]||null,relatedId:related.slice(1).join(':')||null,updatedAt:new Date().toISOString()};if(!record.title){form.querySelector('[role=alert]').textContent='Add a title.';return;}const i=state.notes.findIndex(n=>n.id===record.id);if(i<0)state.notes.push(record);else state.notes[i]=record;persistAnd(renderNotesTool);dialog.close();};
    dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();form.elements.title.focus();
  }
  function renderNotes(){
    const host=get('travelNotesList');if(!host)return;const notes=HVJourney.scoped(state.notes||[],state.activeProfileId).filter(n=>!noteTripFilter||n.tripId===noteTripFilter).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||String(b.date||b.updatedAt||'').localeCompare(String(a.date||a.updatedAt||'')));
    host.innerHTML=notes.length?notes.map(n=>`<article class="travel-note-card" data-note="${E(n.id)}"><div class="travel-note-head"><div><p class="eyebrow">${E(n.category||'NOTE')}${n.pinned?' · PINNED':''}</p><h3>${E(n.title)}</h3></div><button class="text-btn" type="button" data-edit-note="${E(n.id)}">Edit</button></div><div class="travel-note-meta">${n.tripId?'<span>'+E(tripLabel(n.tripId))+'</span>':''}${n.date?'<span>'+E(formatDate(n.date))+'</span>':''}${relationLabel(n)?'<span>'+E(relationLabel(n))+'</span>':''}</div><div class="travel-note-body">${noteBody(n.body)}</div></article>`).join(''):'<p class="empty-state">No notes here yet. Add practical information you want beside the trip rather than buried in another app.</p>';
    host.querySelectorAll('[data-edit-note]').forEach(b=>b.onclick=()=>openNote(state.notes.find(n=>n.id===b.dataset.editNote)));
  }
  function smartItems(tripId){
    if(!tripId)return[];const items=[];if((state.transports||[]).some(t=>t.tripId===tripId&&t.type==='flight'&&t.status!=='cancelled'))items.push('Check in for flight');if((state.accommodations||[]).some(a=>a.tripId===tripId))items.push('Confirm accommodation');const countries=[...new Set((state.stays||[]).filter(s=>s.tripId===tripId).map(s=>s.countryName).filter(Boolean))];if(countries.length)items.push('Review entry requirements for '+countries.join(', '));return items;
  }
  function newChecklist(){
    const dialog=document.createElement('dialog');dialog.className='dialog small-dialog travel-tool-dialog';dialog.setAttribute('aria-label','New travel checklist');
    dialog.innerHTML=`<form class="dialog-card"><div class="dialog-head"><div><p class="eyebrow">CHECKLIST</p><h2>Create checklist</h2></div><button type="button" class="icon-btn" data-close>×</button></div><label class="field"><span>Starting point</span><select name="template">${Object.entries(templates).map(([key,t])=>'<option value="'+key+'">'+E(t.title)+'</option>').join('')}</select></label><label class="field"><span>Trip <em>optional</em></span><select name="tripId">${tripOptions(noteTripFilter,'Across all travel')}</select></label><label class="field"><span>Checklist name</span><input name="title" maxlength="120" required value="Before departure"></label><p class="helper">Herald will add trip-specific suggestions when it knows there is a flight, accommodation or a destination to review. They are reminders, not claims about legal requirements.</p><div class="dialog-actions"><div class="spacer"></div><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Create checklist</button></div></form>`;
    document.body.append(dialog);const form=dialog.querySelector('form'),syncTitle=()=>{form.elements.title.value=templates[form.elements.template.value].title;};form.elements.template.onchange=syncTitle;
    dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());
    form.onsubmit=e=>{e.preventDefault();const template=templates[form.elements.template.value],tripId=form.elements.tripId.value||null,sections=template.sections.map(([name])=>({id:uid(),name})),items=[];template.sections.forEach(([name,list],s)=>list.forEach((text,i)=>items.push({id:uid(),text,sectionId:sections[s].id,done:false,order:i})));const smart=smartItems(tripId);if(smart.length){let section=sections.find(s=>/departure|booking/i.test(s.name));if(!section){section={id:uid(),name:'Trip-specific'};sections.push(section);}for(const text of smart)if(!items.some(i=>i.text.toLowerCase()===text.toLowerCase()))items.push({id:uid(),text,sectionId:section.id,done:false,order:items.filter(i=>i.sectionId===section.id).length,smart:true});}state.checklists.push({id:uid(),profileId:state.activeProfileId,title:form.elements.title.value.trim()||template.title,tripId,template:form.elements.template.value,hideCompleted:false,sections,items,updatedAt:new Date().toISOString()});persistAnd(renderNotesTool);dialog.close();};
    dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
  }
  function duplicateChecklist(list){const copy={...list,id:uid(),title:list.title+' copy',sections:list.sections.map(s=>({...s,id:uid()})),items:[]};const map=new Map(list.sections.map((s,i)=>[s.id,copy.sections[i].id]));copy.items=list.items.map(i=>({...i,id:uid(),sectionId:map.get(i.sectionId)||copy.sections[0]?.id}));state.checklists.push(copy);persistAnd(renderNotesTool);}
  function moveItem(list,item,delta){const siblings=list.items.filter(i=>i.sectionId===item.sectionId).sort((a,b)=>(a.order||0)-(b.order||0)),at=siblings.findIndex(i=>i.id===item.id),other=siblings[at+delta];if(!other)return;const order=item.order||0;item.order=other.order||0;other.order=order;persistAnd(renderNotesTool);}
  function renderChecklists(){
    const host=get('travelChecklistList');if(!host)return;const lists=HVJourney.scoped(state.checklists||[],state.activeProfileId).filter(c=>!noteTripFilter||c.tripId===noteTripFilter);
    host.innerHTML=lists.length?lists.map(list=>{const shown=(list.items||[]).filter(i=>!list.hideCompleted||!i.done),done=(list.items||[]).filter(i=>i.done).length;return `<article class="travel-checklist-card" data-checklist="${E(list.id)}"><div class="travel-checklist-head"><div><p class="eyebrow">CHECKLIST · ${done}/${(list.items||[]).length}</p><h3>${E(list.title)}</h3></div><div class="tool-card-actions"><button class="text-btn" type="button" data-duplicate>Duplicate</button><button class="danger-link" type="button" data-delete>Delete</button></div></div><label class="field compact-field"><span>Trip</span><select data-checklist-trip>${tripOptions(list.tripId||'','Across all travel')}</select></label><div class="checklist-controls"><button class="secondary compact" type="button" data-add-item>+ Item</button><button class="secondary compact" type="button" data-add-section>+ Section</button><button class="text-btn" type="button" data-toggle-completed>${list.hideCompleted?'Show completed':'Hide completed'}</button></div>${(list.sections||[]).map(section=>`<section class="checklist-section"><h4>${E(section.name)}</h4>${shown.filter(i=>i.sectionId===section.id).sort((a,b)=>(a.order||0)-(b.order||0)).map(item=>`<div class="checklist-item ${item.done?'is-done':''}" data-item="${E(item.id)}"><label><input type="checkbox" ${item.done?'checked':''}><span>${E(item.text)}</span>${item.smart?'<small>Suggested from this trip</small>':''}</label><div><button type="button" data-move="-1" aria-label="Move item up">↑</button><button type="button" data-move="1" aria-label="Move item down">↓</button><button type="button" data-remove aria-label="Remove item">×</button></div></div>`).join('')||'<p class="helper">No items in this section.</p>'}</section>`).join('')}</article>`;}).join(''):'<p class="empty-state">Create a checklist from a useful travel starting point, or start with a blank one.</p>';
    host.querySelectorAll('[data-checklist]').forEach(card=>{const list=state.checklists.find(c=>c.id===card.dataset.checklist);if(!list)return;
      card.querySelector('[data-checklist-trip]').onchange=e=>{list.tripId=e.target.value||null;const suggestions=smartItems(list.tripId);if(suggestions.length){let section=list.sections.find(s=>s.name==='Trip-specific');if(!section){section={id:uid(),name:'Trip-specific'};list.sections.push(section);}for(const text of suggestions)if(!list.items.some(i=>i.text.toLowerCase()===text.toLowerCase()))list.items.push({id:uid(),text,sectionId:section.id,done:false,order:list.items.filter(i=>i.sectionId===section.id).length,smart:true});}persistAnd(renderNotesTool);};
      card.querySelector('[data-duplicate]').onclick=()=>duplicateChecklist(list);card.querySelector('[data-delete]').onclick=()=>{if(confirm('Delete this checklist?')){state.checklists=state.checklists.filter(c=>c.id!==list.id);persistAnd(renderNotesTool);}};
      card.querySelector('[data-toggle-completed]').onclick=()=>{list.hideCompleted=!list.hideCompleted;persistAnd(renderNotesTool);};
      card.querySelector('[data-add-section]').onclick=()=>{const name=prompt('Section name');if(name?.trim()){list.sections.push({id:uid(),name:name.trim()});persistAnd(renderNotesTool);}};
      card.querySelector('[data-add-item]').onclick=()=>{const text=prompt('Checklist item');if(text?.trim()){let section=list.sections[0];if(!section){section={id:uid(),name:'Checklist'};list.sections.push(section);}list.items.push({id:uid(),text:text.trim(),sectionId:section.id,done:false,order:list.items.filter(i=>i.sectionId===section.id).length});persistAnd(renderNotesTool);}};
      card.querySelectorAll('[data-item]').forEach(row=>{const item=list.items.find(i=>i.id===row.dataset.item);row.querySelector('input').onchange=e=>{item.done=e.target.checked;item.completedAt=item.done?new Date().toISOString():null;persistAnd(renderNotesTool);};row.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveItem(list,item,Number(b.dataset.move)));row.querySelector('[data-remove]').onclick=()=>{list.items=list.items.filter(i=>i.id!==item.id);persistAnd(renderNotesTool);};});
    });
  }
  function renderNotesTool(){
    ensure();const host=get('notesChecklistTool');if(!host)return;
    host.innerHTML=`<header class="tool-page-heading"><div><p class="eyebrow">TRAVEL TOOLS</p><h2>Notes &amp; Checklist</h2><p>Keep the practical details beside the journey they belong to.</p></div><div class="tool-page-actions"><button class="secondary" id="newChecklistBtn" type="button">New checklist</button><button class="primary" id="newNoteBtn" type="button">New note</button></div></header>
      <label class="field tool-scope"><span>Show</span><select id="notesTripFilter">${tripOptions(noteTripFilter,'All travel')}</select></label>
      <div class="travel-tool-columns"><article class="panel"><div class="panel-head"><div><p class="eyebrow">REFERENCE</p><h2>Travel notes</h2></div></div><div id="travelNotesList"></div></article><article class="panel"><div class="panel-head"><div><p class="eyebrow">BEFORE YOU GO</p><h2>Checklists</h2></div></div><div id="travelChecklistList"></div></article></div>`;
    get('notesTripFilter').onchange=e=>{noteTripFilter=e.target.value;renderNotesTool();};get('newNoteBtn').onclick=()=>openNote();get('newChecklistBtn').onclick=newChecklist;renderNotes();renderChecklists();
  }

  function budgetFor(tripId){return (state.budgets||[]).find(b=>b.tripId===tripId&&b.profileId===state.activeProfileId);}
  function ensureBudget(tripId){let b=budgetFor(tripId);if(!b){b={id:uid(),tripId,profileId:state.activeProfileId,baseCurrency:'GBP',targetAmount:null,travellers:1,createdAt:new Date().toISOString()};state.budgets.push(b);}return b;}
  const n=value=>value===''||value==null?null:Number(value);
  function baseValue(item,field,budget){const value=Number(item[field]);if(!Number.isFinite(value))return null;if(item.currency===budget.baseCurrency)return value;const rate=Number(item.rate);return Number.isFinite(rate)&&rate>0?value*rate:null;}
  function money(amount,currency){if(!Number.isFinite(Number(amount)))return'—';return HVPrices.format({amount:Number(amount),currency});}
  function sourceRows(tripId){
    const rows=[];for(const a of state.accommodations||[]){if(a.tripId!==tripId)continue;const p=HVPrices.price(a);if(p)rows.push({sourceType:'accommodation',sourceId:a.id,label:a.propertyName||a.location||'Accommodation',category:'Accommodation',price:p});}
    for(const t of state.transports||[]){if(t.tripId!==tripId)continue;const p=HVPrices.price(t);if(!p)continue;const category=t.type==='flight'?'Flights':t.type==='train'?'Trains':t.type==='bus'?'Buses':t.type==='boat'?'Ferries':t.type==='car'?'Car hire':'Taxis';rows.push({sourceType:'transport',sourceId:t.id,label:HVJourney.transportLabel(t,window.HVJourneys?.airportFor)||HVJourney.types[t.type],category,price:p});}return rows;
  }
  function openExpense(existing={},kind='planned'){
    const tripId=budgetTripId||existing.tripId;if(!tripId)return;const budget=ensureBudget(tripId),item=existing,dialog=document.createElement('dialog');dialog.className='dialog travel-tool-dialog';dialog.setAttribute('aria-label',item.id?'Edit budget item':'Add budget item');
    const currency=item.currency||budget.baseCurrency,foreign=currency!==budget.baseCurrency;
    dialog.innerHTML=`<form class="dialog-card budget-item-form"><div class="dialog-head"><div><p class="eyebrow">${kind==='daily'?'DAILY SPEND':'TRIP BUDGET'}</p><h2>${item.id?'Edit cost':kind==='daily'?'Record expense':'Add planned cost'}</h2></div><button type="button" class="icon-btn" data-close>×</button></div>
      <label class="field"><span>Item</span><input name="label" maxlength="140" required value="${E(item.label)}"></label>
      <div class="form-grid"><label class="field"><span>Category</span><select name="category">${expenseCategories.map(c=>'<option '+(c===(item.category||'Other')?'selected':'')+'>'+E(c)+'</option>').join('')}</select></label><label class="field"><span>Date <em>optional</em></span><input type="date" name="date" value="${E(item.date||'')}"></label></div>
      <div class="form-grid"><label class="field"><span>Planned</span><input name="planned" type="number" min="0" step="any" inputmode="decimal" value="${Number.isFinite(item.planned)?item.planned:''}" ${kind==='daily'&&!item.id?'disabled':''}></label><label class="field"><span>Actual</span><input name="actual" type="number" min="0" step="any" inputmode="decimal" value="${Number.isFinite(item.actual)?item.actual:''}"></label></div>
      <div class="form-grid"><label class="field"><span>Currency</span><select name="currency">${[...new Set([budget.baseCurrency,currency,...HVPrices.currencies])].map(c=>'<option '+(c===currency?'selected':'')+'>'+c+'</option>').join('')}</select></label><label class="field"><span>Payment status</span><select name="paymentStatus">${paymentStates.map(s=>'<option '+(s===(item.paymentStatus||'Not booked')?'selected':'')+'>'+E(s)+'</option>').join('')}</select></label></div>
      <div data-rate-wrap><label class="field"><span>Conversion rate <em>only when currencies differ</em></span><input name="rate" type="number" min="0" step="any" inputmode="decimal" value="${Number.isFinite(item.rate)?item.rate:''}" placeholder="1 ${E(currency)} = ? ${E(budget.baseCurrency)}"></label><p class="helper">Herald keeps the original amount. Enter a rate if you want this item included in ${E(budget.baseCurrency)} totals. <a data-xe-budget target="_blank" rel="noopener noreferrer">Check XE ↗</a></p></div>
      <label class="check-row compact-check"><input name="included" type="checkbox" ${item.included!==false?'checked':''}><span><strong>Include in budget totals</strong><small>You can keep a record without counting it.</small></span></label>
      <p class="form-error" role="alert"></p><div class="dialog-actions">${item.id?'<button type="button" class="danger-link" data-delete>Delete</button>':''}<div class="spacer"></div><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save</button></div></form>`;
    document.body.append(dialog);const form=dialog.querySelector('form'),rateWrap=dialog.querySelector('[data-rate-wrap]');
    const updateCurrency=()=>{const cur=form.elements.currency.value;rateWrap.hidden=cur===budget.baseCurrency;const link=dialog.querySelector('[data-xe-budget]');link.href='https://www.xe.com/currencyconverter/convert/?'+new URLSearchParams({Amount:form.elements.actual.value||form.elements.planned.value||1,From:cur,To:budget.baseCurrency});};form.elements.currency.onchange=updateCurrency;form.elements.actual.oninput=updateCurrency;form.elements.planned.oninput=updateCurrency;updateCurrency();
    dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.querySelector('[data-delete]')?.addEventListener('click',()=>{if(confirm('Delete this budget item?')){state.expenses=state.expenses.filter(e=>e.id!==item.id);persistAnd(renderBudgetTool);dialog.close();}});
    form.onsubmit=e=>{e.preventDefault();const planned=form.elements.planned.disabled?null:n(form.elements.planned.value),actual=n(form.elements.actual.value),record={...item,id:item.id||uid(),budgetId:budget.id,tripId,profileId:state.activeProfileId,label:form.elements.label.value.trim(),category:form.elements.category.value||'Other',planned,actual,currency:form.elements.currency.value,rate:form.elements.currency.value===budget.baseCurrency?1:n(form.elements.rate.value),paymentStatus:form.elements.paymentStatus.value,date:form.elements.date.value||null,included:form.elements.included.checked,kind:item.kind||kind,updatedAt:new Date().toISOString()};if(!record.label||(!Number.isFinite(record.planned)&&!Number.isFinite(record.actual))){form.querySelector('[role=alert]').textContent='Add a name and a planned or actual amount.';return;}const i=state.expenses.findIndex(x=>x.id===record.id);if(i<0)state.expenses.push(record);else state.expenses[i]=record;persistAnd(renderBudgetTool);dialog.close();};
    dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();form.elements.label.focus();
  }
  function importSource(source){
    const budget=ensureBudget(budgetTripId);if(state.expenses.some(e=>e.sourceType===source.sourceType&&e.sourceId===source.sourceId&&e.tripId===budgetTripId))return;state.expenses.push({id:uid(),budgetId:budget.id,tripId:budgetTripId,profileId:state.activeProfileId,label:source.label,category:source.category,planned:source.price.amount,actual:null,currency:source.price.currency,rate:source.price.currency===budget.baseCurrency?1:null,paymentStatus:'Booked',included:true,sourceType:source.sourceType,sourceId:source.sourceId,kind:'planned',updatedAt:new Date().toISOString()});persistAnd(renderBudgetTool);
  }
  function renderBudgetContent(){
    const host=get('budgetContent');if(!host)return;if(!budgetTripId){host.innerHTML='<article class="panel"><p class="empty-state">Choose a trip to see its saved travel costs and build a budget.</p></article>';return;}
    const budget=budgetFor(budgetTripId)||{baseCurrency:'GBP',targetAmount:null,travellers:1},items=(state.expenses||[]).filter(e=>e.tripId===budgetTripId&&e.profileId===state.activeProfileId),included=items.filter(e=>e.included!==false),missing=new Set(),sum=field=>included.reduce((total,item)=>{const value=baseValue(item,field,budget);if(Number.isFinite(Number(item[field]))&&value==null)missing.add(item.id);return total+(value||0);},0),planned=sum('planned'),actual=sum('actual'),target=Number.isFinite(Number(budget.targetAmount))?Number(budget.targetAmount):planned,remaining=target-actual;
    const paid=included.filter(e=>['Paid','Refunded'].includes(e.paymentStatus)).reduce((t,e)=>t+(baseValue(e,'actual',budget)||baseValue(e,'planned',budget)||0),0),outstanding=Math.max(0,actual-paid),tripRecord=trip(budgetTripId),dates=[...(state.stays||[]).filter(s=>s.tripId===budgetTripId).flatMap(s=>[s.start,s.end]),...(state.transports||[]).filter(t=>t.tripId===budgetTripId).flatMap(t=>[t.startLocal?.slice(0,10),t.endLocal?.slice(0,10)])].filter(Boolean).sort(),days=dates.length?Math.max(1,Math.round((Date.parse(dates.at(-1))-Date.parse(dates[0]))/86400000)+1):null,travellers=Math.max(1,Number(budget.travellers)||1),sources=sourceRows(budgetTripId),imported=new Set(items.map(e=>e.sourceType+':'+e.sourceId)),available=sources.filter(s=>!imported.has(s.sourceType+':'+s.sourceId));
    const summary=[['Budget',money(target,budget.baseCurrency)],['Planned',money(planned,budget.baseCurrency)],['Spent',money(actual,budget.baseCurrency)],['Remaining',money(remaining,budget.baseCurrency)],['Paid',money(paid,budget.baseCurrency)],['Outstanding',money(outstanding,budget.baseCurrency)]];
    const row=item=>{const p=baseValue(item,'planned',budget),a=baseValue(item,'actual',budget),converted=item.currency!==budget.baseCurrency&&((p!=null)||(a!=null));return `<div class="budget-row" data-expense="${E(item.id)}"><div><strong>${E(item.label)}</strong><span>${E(item.category)}${item.date?' · '+E(formatDate(item.date)):''}${item.sourceType?' · from Herald record':''}</span></div><div><span>Planned</span><strong>${money(item.planned,item.currency)}</strong>${converted&&p!=null?'<small>≈ '+money(p,budget.baseCurrency)+'</small>':''}</div><div><span>Actual</span><strong>${money(item.actual,item.currency)}</strong>${converted&&a!=null?'<small>≈ '+money(a,budget.baseCurrency)+'</small>':''}</div><div class="budget-row-status"><span>${E(item.paymentStatus||'Not booked')}</span>${item.included===false?'<small>Excluded</small>':''}</div><button type="button" class="text-btn" data-edit-expense="${E(item.id)}">Edit</button></div>`;};
    const categories=new Map();for(const item of included){const value=baseValue(item,'actual',budget);if(value!=null)categories.set(item.category,(categories.get(item.category)||0)+value);}const max=Math.max(1,...categories.values());
    host.innerHTML=`<div class="budget-summary">${summary.map(([label,value])=>'<article><span>'+label+'</span><strong>'+E(value)+'</strong></article>').join('')}</div>
      ${missing.size?'<p class="budget-conversion-warning">'+missing.size+' item'+(missing.size===1?'':'s')+' need a conversion rate before they can be included in '+E(budget.baseCurrency)+' totals.</p>':''}
      <div class="budget-layout"><article class="panel"><div class="panel-head"><div><p class="eyebrow">TRIP COSTS</p><h2>Planned vs actual</h2></div><div class="tool-page-actions"><button class="secondary compact" id="recordDailyBtn" type="button">Record expense</button><button class="primary compact" id="addBudgetItemBtn" type="button">Add cost</button></div></div><div class="budget-table">${items.length?items.map(row).join(''):'<p class="empty-state">No budget items yet. Use saved travel costs below or add a planned amount.</p>'}</div></article>
      <aside><article class="panel budget-settings"><p class="eyebrow">TRIP BUDGET</p><h2>Settings</h2><form id="budgetSettingsForm"><label class="field"><span>Total budget <em>optional</em></span><input name="target" type="number" min="0" step="any" value="${Number.isFinite(Number(budget.targetAmount))?budget.targetAmount:''}"></label><div class="form-grid"><label class="field"><span>Currency</span><select name="baseCurrency">${[...new Set([budget.baseCurrency,...HVPrices.currencies])].map(c=>'<option '+(c===budget.baseCurrency?'selected':'')+'>'+c+'</option>').join('')}</select></label><label class="field"><span>Travellers</span><input name="travellers" type="number" min="1" max="100" value="${travellers}"></label></div><button class="secondary wide">Save budget settings</button></form><div class="budget-useful-metrics">${days?'<span>Cost per day <strong>'+money(actual/days,budget.baseCurrency)+'</strong></span>':''}<span>Cost per traveller <strong>${money(actual/travellers,budget.baseCurrency)}</strong></span></div></article>
      <article class="panel"><p class="eyebrow">FROM THIS TRIP</p><h2>Existing Herald costs</h2><p class="helper">Hotel and transport prices already saved in Herald can be added without typing them again.</p><div class="budget-source-list">${available.length?available.map((s,i)=>'<div><span><strong>'+E(s.label)+'</strong><small>'+money(s.price.amount,s.price.currency)+'</small></span><button class="text-btn" type="button" data-import-source="'+i+'">Add to budget</button></div>').join(''):'<p class="empty-state">All priced travel records are already included, or this trip has no saved prices yet.</p>'}</div></article>
      <article class="panel"><p class="eyebrow">SPEND BY CATEGORY</p><h2>Actual spend</h2><div class="budget-category-list">${categories.size?[...categories].sort((a,b)=>b[1]-a[1]).map(([name,value])=>'<div><span>'+E(name)+'</span><div><i style="width:'+Math.max(3,value/max*100)+'%"></i></div><strong>'+E(money(value,budget.baseCurrency))+'</strong></div>').join(''):'<p class="empty-state">Actual spend will appear here as you record it.</p>'}</div></article></aside></div>
      <article class="panel daily-spend"><div class="panel-head"><div><p class="eyebrow">ON THE ROAD</p><h2>Daily spending</h2></div><button class="secondary compact" id="recordDailyBtnBottom" type="button">+ Record expense</button></div>${items.filter(i=>i.kind==='daily').sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).map(row).join('')||'<p class="empty-state">Record metro tickets, meals, museums, taxis and other day-to-day spend here.</p>'}</article>`;
    get('addBudgetItemBtn').onclick=()=>openExpense({},'planned');get('recordDailyBtn').onclick=get('recordDailyBtnBottom').onclick=()=>openExpense({date:new Date().toISOString().slice(0,10)},'daily');
    host.querySelectorAll('[data-edit-expense]').forEach(b=>b.onclick=()=>{const item=state.expenses.find(e=>e.id===b.dataset.editExpense);openExpense(item,item.kind||'planned');});
    host.querySelectorAll('[data-import-source]').forEach(b=>b.onclick=()=>importSource(available[Number(b.dataset.importSource)]));
    get('budgetSettingsForm').onsubmit=e=>{e.preventDefault();const b=ensureBudget(budgetTripId),f=e.currentTarget.elements;b.targetAmount=n(f.target.value);b.baseCurrency=f.baseCurrency.value;b.travellers=Math.max(1,Number(f.travellers.value)||1);for(const item of state.expenses.filter(x=>x.tripId===budgetTripId&&x.currency===b.baseCurrency))item.rate=1;persistAnd(renderBudgetTool);};
  }
  function renderBudgetTool(){
    ensure();const host=get('budgetPlannerTool');if(!host)return;const trips=HVJourney.scoped(state.trips||[],state.activeProfileId);if(!budgetTripId||!trips.some(t=>t.id===budgetTripId))budgetTripId=trips[0]?.id||'';
    host.innerHTML=`<header class="tool-page-heading"><div><p class="eyebrow">TRAVEL TOOLS</p><h2>Budget Planner</h2><p>Choose a trip, bring in costs Herald already knows, then compare the plan with what you actually spend.</p></div></header><label class="field tool-scope"><span>Trip</span><select id="budgetTripSelect"><option value="">Choose a trip</option>${trips.map(t=>'<option value="'+E(t.id)+'" '+(t.id===budgetTripId?'selected':'')+'>'+E(t.name||'Untitled trip')+'</option>').join('')}</select></label><div id="budgetContent"></div>`;
    get('budgetTripSelect').onchange=e=>{budgetTripId=e.target.value;renderBudgetContent();};renderBudgetContent();
  }
  function renderCurrent(){const view=document.body.dataset.currentView;if(view==='notes')renderNotesTool();if(view==='budget')renderBudgetTool();}
  document.addEventListener('DOMContentLoaded',()=>{ensure();renderCurrent();});
  window.addEventListener('hv-data-changed',renderCurrent);
  window.addEventListener('hashchange',()=>queueMicrotask(renderCurrent));
  document.addEventListener('hv-route',renderCurrent);
  window.HVTravelTools={renderNotesTool,renderBudgetTool};
})();
