/* Official-rule reminders. Never infer passport nationality from residence. */
(() => {
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let loaded=false;
 function info(stay){const profile=(state.profiles||[]).find(p=>p.id===(stay.profileId||state.activeProfileId)),trip=state.trips.find(t=>t.id===stay.tripId),codes=profile?.citizenships||[],passport=trip?.visaPassportCode||stay.visaPassportCode||(codes.length===1?codes[0]:'');
   const rule=passport?HVEntryRules.lookup(passport,stay.countryCode,{days:daysInclusive(stay.start,stay.end)}):null,detail=rule||{title:'Check official requirements',tone:'neutral'},own=passport===stay.countryCode;
   const fingerprint=JSON.stringify([passport,stay.countryCode,rule?.requirement||'unknown',rule?.days||'',rule?.source||'']);
   const id=[profile?.id||'shared',passport||'unconfirmed',stay.countryCode,stay.tripId||stay.id].join(':');
   const acknowledged=(state.visaAcknowledgements||[]).some(a=>(a.id===id||((a.profileId||null)===(profile?.id||null)&&a.passport===passport&&a.destination===stay.countryCode&&(stay.tripId?a.tripId===stay.tripId:a.stayId===stay.id)))&&a.fingerprint===fingerprint);
   return {profile,trip,codes,passport,rule,detail,own,id,fingerprint,acknowledged,needs:!own&&(!passport||!rule||['warn','bad','neutral'].includes(detail.tone))};
 }
 function indicator(s){const i=info(s);return i.needs&&!i.acknowledged?`<button type="button" class="calendar-visa-notice" data-visa-notice="${E(s.id)}" aria-label="${i.passport&&i.rule?'Review visa information':'Check passport and entry requirements'}" title="Entry requirements">!</button>`:'';}
 const detailLink=s=>`<button type="button" class="text-btn" data-visa-notice="${E(s.id)}">Entry requirements</button>`;
 function open(id){const s=state.stays.find(r=>r.id===id);if(!s)return;const d=document.createElement('dialog');d.className='dialog';d.setAttribute('aria-label','Entry requirements');document.body.append(d);
 function render(){const i=info(s);d.innerHTML=`<div class="dialog-card"><div class="dialog-head"><h2>Entry requirements</h2><button class="text-btn" type="button" data-close>Close ×</button></div><p>${E(s.countryName)} · ${i.passport?E(countryByCode(i.passport)?.name||i.passport)+' passport':'Confirm your passport nationality'}</p>${`<label class="field"><span>Passport used for this journey</span><input list="countryList" name="passport" placeholder="Passport country" value="${E(countryByCode(i.passport)?.name||i.passport)}"></label><button class="secondary" type="button" data-passport>Confirm passport</button><p data-passport-error role="alert"></p>`}<h3>${E(i.own?'Your passport country':!i.passport?'Confirm your passport first':i.rule?i.detail.title:'Check official requirements')}</h3><p>${!i.passport?'Your home country may differ from your passport nationality.':i.own?'This is your citizenship destination. Check the travel document needed for entry.':i.rule?E(i.rule.text):'Reliable visa information is unavailable for this passport and destination. Check with the destination’s official immigration authority or embassy.'}</p>${i.rule?`<p class="helper">Reviewed guidance: ${E(i.rule.requirement)}${i.rule.days?' · '+E(i.rule.days)+' days':''}. Acknowledging this reminder does not mean you hold a visa.</p><a href="${E(i.rule?.source||'https://www.gov.uk/foreign-travel-advice')}" target="_blank" rel="noopener">Official source</a>`:''}<p>${i.passport==='GB'?'<a href="https://www.gov.uk/foreign-travel-advice" target="_blank" rel="noopener">Official UK foreign travel advice and entry guidance</a>':'<a href="https://apply.joinsherpa.com/visa" target="_blank" rel="noopener">Open existing live requirements checker</a>'}</p>${i.passport?'<button class="primary" type="button" data-ack>I have read this information</button>':''}</div>`;
 d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('[data-passport]')?.addEventListener('click',()=>{const country=countryByName(d.querySelector('[name=passport]').value);if(!country||country.code==='SEA'){d.querySelector('[data-passport-error]').textContent='Choose your passport country.';return;}(i.trip||s).visaPassportCode=country.code;persist();render();HVCalendar.renderMonth();});d.querySelector('[data-ack]')?.addEventListener('click',()=>{state.visaAcknowledgements||=[];const row={id:i.id,profileId:i.profile?.id||null,tripId:s.tripId||null,stayId:s.id,passport:i.passport,destination:s.countryCode,fingerprint:i.fingerprint};const old=state.visaAcknowledgements.find(a=>a.id===i.id);if(old)Object.assign(old,row);else state.visaAcknowledgements.push(row);persist();d.close();HVCalendar.renderMonth();});}
 d.onclose=()=>d.remove();render();d.showModal();}
 function load(){if(loaded)return;loaded=true;window.HVCalendar?.renderMonth();}
 window.HVVisaNotices={indicator,detailLink,info};document.addEventListener('click',e=>{const b=e.target.closest('[data-visa-notice]');if(b){e.preventDefault();e.stopPropagation();open(b.dataset.visaNotice);}});document.addEventListener('DOMContentLoaded',load);
})();
