/* End-to-end brief checks use fictional data and deterministic network responses. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),binary=require('@sparticuz/chromium');binary.setGraphicsMode=false;
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results/master');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)&&p!==root){res.writeHead(403);res.end();return;}if(!path.extname(p))p=path.join(p,'index.html');try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});
const seed={version:2,activeProfileId:'p',profiles:[{id:'p',name:'Fictional traveller',citizenships:['GB'],enabledRules:['schengen']}],trips:[],stays:[],transports:[],accommodations:[],placeVisits:[],residences:[],savedPlaces:[]};
async function moreDetails(container){const more=container.locator('.transport-more');if(!await more.evaluate(el=>el.open))await more.locator('summary').click();}
let browser;
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({executablePath:process.env.HV_CHROMIUM_PATH||await binary.executablePath(),args:binary.args.filter(a=>a!=='--single-process'),headless:true});
 for(const width of [390,1440]){let searchRequests=0;
  const page=await browser.newPage({viewport:{width,height:960},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install({time:new Date('2026-10-02T12:00:00Z')});
  await page.route('**/*',r=>{const url=r.request().url();if(url.startsWith(origin))return r.continue();
   if(url.includes('photon.komoot.io/')){searchRequests++;const term=new URL(url).searchParams.get('q')||'',city=term.includes('Peter')?'Peterborough':term.includes('Cambridge')?'Cambridge':'Stansted Airport';const props=(name,type,id)=>({osm_type:'N',osm_id:id,name,osm_value:type,street:'Station Road',city,country:'United Kingdom',countrycode:'gb'});return r.fulfill({json:{features:[{geometry:{coordinates:[-.25,52.5]},properties:props(city,'city',1)},{geometry:{coordinates:[-.24,52.57]},properties:props(city+' railway station','station',city==='Cambridge'?3:city==='Peterborough'?4:2)}]}});}
   return r.abort();
  });
  await page.addInitScript(data=>{if(!localStorage.getItem('whereIveBeen.data.v2'))localStorage.setItem('whereIveBeen.data.v2',JSON.stringify(data));},seed);
  await page.goto(origin+'/#/calendar');await page.waitForFunction(()=>window.HVCalendar?.ready&&window.HVTravelSearch);
  await page.waitForFunction(()=>HVJourneys.airports().length);await page.evaluate(()=>HVJourneys.openTransport());
  assert.equal(await page.locator('[data-airport-details=start]').textContent(),'','A blank flight must not show an unrelated airport');
  assert.equal(await page.evaluate(()=>HVJourneys.airportFor('')),null);await page.locator('[data-close-transport]').first().click();
  await page.evaluate(()=>HVJourneys.openTransport(null,{type:'train'}));
  const f=page.locator('#transportForm');
  for(const [side,term]of [['start','Stansted'],['end','Peterborough']]){await f.locator(`[name=${side}name]`).fill(term);await f.locator(`[data-airport-results=${side}] [data-travel-result]`).first().click();assert.match(await f.locator(`[name=${side}name]`).inputValue(),/railway station/);}
  await f.locator('[name=startLocal]').fill('2026-10-10T23:30');await f.locator('[name=endLocal]').fill('2026-10-12T06:30');
  await f.locator('[data-ground-add]').click();await f.locator('[data-via-field=name]').fill('Cambridge');await f.locator('[data-via-results] [data-travel-result]').first().click();
  await f.locator('[data-via-field=arrivalLocal]').fill('2026-10-11T09:00');await f.locator('[data-via-field=departureLocal]').fill('2026-10-11T10:00');
  await f.locator('.transport-extras details summary').click();await f.locator('[name=operator]').fill('Fictional Rail');await f.locator('[name=serviceNumber]').fill('R123');await moreDetails(f);await f.locator('[name=notes]').fill('Platform 4\nKeep both tickets');await f.locator('[name=priceAmount]').fill('25.50');
  await f.locator('[name=addReturn]').check();await f.locator('[type=submit]').click();
  assert.equal(await page.evaluate(()=>state.transports.length),0,'Outbound is held until both journeys are valid');assert.match(await f.locator('[name=startname]').inputValue(),/Peterborough/);assert.equal(await f.locator('[name=startLocal]').inputValue(),'','Return times require an independent choice');assert.equal(await f.locator('[name=notes]').inputValue(),'');
  await f.locator('[name=startLocal]').fill('2026-10-20T08:00');await f.locator('[name=endLocal]').fill('2026-10-20T10:00');await f.locator('.transport-extras details summary').click();await f.locator('[name=operator]').fill('Different Rail');await f.locator('[name=priceAmount]').fill('30');await f.locator('[name=priceCurrency]').selectOption('EUR');await f.locator('[type=submit]').click();
  const records=await page.evaluate(()=>state.transports);assert.equal(records.length,2);assert.equal(records[0].via[0].name,'Cambridge railway station');assert.equal(records[0].start.address,'Station Road, Stansted Airport, United Kingdom');assert.equal(records[0].notes,'Platform 4\nKeep both tickets');assert.deepEqual(records[0].price,{amount:25.5,currency:'GBP'});assert.equal(records[0].relatedTransportId,records[1].id);assert.equal(records[1].operator,'Different Rail');assert.deepEqual(records[1].price,{amount:30,currency:'EUR'});
  for(const date of ['2026-10-10','2026-10-11','2026-10-12'])assert.ok(await page.locator(`[data-calendar-date="${date}"] .calendar-day-transport`).count(),'Multi-day journey on '+date);
  await page.evaluate(()=>HVPlaces.open({accommodation:true,place:{id:'test-hotel',name:'Fictional House Sit',lat:52,lon:0,countryCode:'GB',countryName:'United Kingdom',address:'10 Test Lane'},date:'2026-10-10',end:'2026-10-12'}));
  const p=page.locator('.place-search-dialog');assert.equal(await p.locator('[name=code]').count(),0);await p.locator('[name=placeType]').selectOption('House Sit');await p.locator('[data-place-details]>summary').click();await p.locator('[name=recordNotes]').fill('Keys with neighbour\nFeed the cat');await p.locator('[name=priceAmount]').fill('0');await p.locator('[type=submit]').click();
  assert.equal(await page.evaluate(()=>state.accommodations[0].type),'House Sit');await page.reload();await page.waitForFunction(()=>window.HVCalendar?.ready);assert.equal(await page.evaluate(()=>state.transports.length),2);assert.equal(await page.evaluate(()=>state.accommodations[0].notes),'Keys with neighbour\nFeed the cat');
  await page.evaluate(()=>{state.transports.push({...state.transports[0],id:'excluded-transfer',price:{amount:300,currency:'GBP'}});state.placeVisits.push({id:'outside-range',profileId:'p',category:'locations',itemId:'outside-place',date:'2026-12-01',status:'visited',place:{name:'Unrelated future location',lat:51,lon:1,countryCode:'GB'}});});
  await page.locator('.day-number[data-calendar-date-select="2026-10-10"]').click();await page.locator('.day-number[data-calendar-date-select="2026-10-12"]').click();await page.locator('[data-create-range-trip]').click();
  const trip=page.locator('dialog[aria-label="Create trip"]');assert.equal(await trip.locator('[data-record-id=outside-range]').count(),0,'Legacy unlinked records outside the dates are excluded');await trip.locator('[name=name]').fill('Fictional railway trip');await trip.locator('[name=notes]').fill('Trip notes\nSecond line');await trip.locator('[data-record-id=excluded-transfer]').uncheck();await trip.locator('[type=submit]').click();
  assert.equal(await page.evaluate(()=>state.trips.length),1);assert.equal(await page.evaluate(()=>state.transports.length),3);assert.equal(await page.evaluate(()=>state.accommodations.length),1);assert.ok(await page.evaluate(()=>!HVCalendar.journeyGroups().find(g=>g.trip?.id===state.trips[0].id).transports.some(t=>t.id==='excluded-transfer')),'Explicit exclusions are not inferred back into the trip');assert.ok(await page.evaluate(()=>state.transports[0].tripId===state.trips[0].id));assert.equal(await page.evaluate(()=>state.transports[1].tripId),null,'Return outside the date range stays standalone');
  const detail=page.locator('dialog[aria-label="Trip details"]');assert.match(await detail.innerText(),/£25.50/);await detail.locator('[data-trip-photos]').setInputFiles(path.join(root,'assets/herald-favicon.png'));await detail.locator('.trip-gallery img').waitFor({timeout:10000});assert.equal(await page.evaluate(()=>state.trips[0].photos.length),1);await detail.locator('[data-close]').click();await page.reload();await page.waitForFunction(()=>window.HVCalendar?.ready);assert.equal(await page.evaluate(()=>state.trips[0].photos.length),1);assert.equal(await page.evaluate(()=>state.trips[0].notes),'Trip notes\nSecond line');
  await page.evaluate(()=>HVJourneys.openTransport('excluded-transfer'));await moreDetails(f);await f.locator('[name=notes]').fill('Edited while excluded');await f.locator('[type=submit]').click();assert.equal(await page.evaluate(()=>state.transports.find(t=>t.id==='excluded-transfer').tripId),null,'Editing an excluded journey does not infer it back into the trip');
  await page.evaluate(()=>{state.profiles.push({id:'q',name:'Second fictional traveller',citizenships:[],enabledRules:['schengen']});state.trips[0].profileIds=['p','q'];HVTrips.edit('2026-10-20','2026-10-20');});
  await trip.locator('[name=name]').fill('Unsaved new trip');await trip.locator('[name=notes]').fill('Draft notes');const savedTripId=await page.evaluate(()=>state.trips[0].id);
  await trip.locator('[name=existing]').selectOption(savedTripId);assert.equal(await trip.locator('[name=name]').inputValue(),'Fictional railway trip');assert.ok(await trip.locator('[name=name]').isDisabled());
  await trip.locator('[name=existing]').selectOption('');assert.equal(await trip.locator('[name=name]').inputValue(),'Unsaved new trip');assert.equal(await trip.locator('[name=notes]').inputValue(),'Draft notes');
  await trip.locator('[name=existing]').selectOption(savedTripId);await trip.locator('[type=submit]').click();
  const extended=await page.evaluate(()=>state.trips[0]);assert.equal(extended.name,'Fictional railway trip');assert.equal(extended.notes,'Trip notes\nSecond line');assert.equal(extended.start,'2026-10-10');assert.equal(extended.end,'2026-10-20');assert.equal(extended.photos.length,1);assert.deepEqual(extended.profileIds,['p','q']);
  assert.equal(await page.evaluate(()=>state.transports.length),3);assert.equal(await page.evaluate(()=>state.transports[1].tripId),savedTripId);assert.match(await detail.innerText(),/€30.00/);await detail.locator('[data-close]').click();
  await page.reload();await page.waitForFunction(()=>window.HVCalendar?.ready);assert.equal(await page.evaluate(()=>state.trips[0].notes),'Trip notes\nSecond line');
  const cell=page.locator('[data-calendar-date="2026-10-10"]').first();await cell.scrollIntoViewIfNeeded();await page.waitForTimeout(100);const box=await cell.boundingBox();await cell.locator('.calendar-day-transport').first().hover();await page.locator('#calendarFloatingDetail').waitFor();assert.match(await page.locator('#calendarFloatingDetail').innerText(),/Fictional Rail/);assert.deepEqual(await cell.boundingBox(),box,'Hover details never move the cell');
  await page.mouse.move(0,0);await page.goto(origin+'/#/dashboard');await page.locator('.brand').click();assert.match(page.url(),/#\/dashboard$/);
  for(const theme of ['light','dark']){await page.evaluate(t=>{document.documentElement.dataset.theme=t;window.dispatchEvent(new Event('themechange'));},theme);assert.equal(await page.locator('.brand-logo-mark').evaluate(img=>img.naturalWidth),2048);}
  await page.evaluate(()=>HVJourneys.openTransport(null,{type:'train'}));const beforeSearch=searchRequests;await page.locator('#transportForm [name=startname]').fill('Peterborough Last');await page.locator('#transportForm [data-travel-result]').first().waitFor();assert.equal(searchRequests-beforeSearch,2,'Reopening forms does not accumulate duplicate live-search handlers');assert.equal(await page.locator('#transportForm [name=priceCurrency]').inputValue(),'GBP');await page.locator('[data-close-transport]').first().click();
  await page.goto(origin+'/#/calendar');await page.waitForFunction(()=>window.HVCalendar?.ready);
  await page.screenshot({path:path.join(out,'transport-calendar-'+width+'.png'),fullPage:true});
  await page.evaluate(()=>{const host=document.createElement('div');host.id='icon-check';host.innerHTML=['flight','boat','bus','car','train','walk','other'].map(t=>HVTransportIcons.html(t)).join('');document.body.append(host);});await page.waitForFunction(()=>[...document.querySelectorAll('#icon-check img')].every(i=>i.complete&&i.naturalWidth));const sizes=await page.locator('#icon-check img').evaluateAll(images=>images.map(i=>({height:i.getBoundingClientRect().height,ratio:i.getBoundingClientRect().width/i.getBoundingClientRect().height,natural:i.naturalWidth/i.naturalHeight})));assert.equal(new Set(sizes.map(i=>i.height)).size,1);for(const i of sizes)assert.ok(Math.abs(i.ratio-i.natural)<.01,'Supplied icon aspect ratio preserved');await page.locator('#icon-check').evaluate(el=>el.remove());
  await page.evaluate(()=>{const a=state.accommodations[0];state.accommodations.push({...a,id:'repeat',tripId:null,checkIn:'2026-11-01',checkOut:'2026-11-02'},{...a,id:'neighbour',tripId:null,propertyName:'Separate neighbouring hotel',placeId:'another-place',place:{...a.place,id:'another-place',name:'Separate neighbouring hotel'},checkIn:'2026-11-01',checkOut:'2026-11-02'});});await page.evaluate(()=>location.hash='/journey-map');await page.waitForSelector('.marker-accommodation');assert.equal(await page.locator('.journey-cluster').count(),0);assert.equal(await page.locator('.marker-accommodation').count(),2,'Only exact-property repeat stays share a marker');assert.equal(await page.locator('.marker-accommodation small').innerText(),'×2');assert.equal(await page.locator('.marker-accommodation').first().evaluate(e=>e.getBoundingClientRect().width),16);
  await page.evaluate(()=>{state.accommodations.find(a=>a.id==='repeat').tripId=state.trips[0].id;HVJourneyMap.open('trip:'+state.trips[0].id);});
  const focusedMap=page.locator('.journey-map-dialog'),repeatMarker=focusedMap.locator('.marker-accommodation').filter({has:page.locator('small')});assert.equal(await repeatMarker.locator('small').innerText(),'×2','Repeat stays also share a counted marker in trip maps');await repeatMarker.click();const popup=focusedMap.locator('.leaflet-popup-content');assert.match(await popup.innerText(),/Stayed 2 times/);assert.match(await popup.innerText(),/10 - 12 Oct 2026/);assert.match(await popup.innerText(),/1 - 2 Nov 2026/);await focusedMap.locator('[data-map-close]').click();
  await page.goto(origin+'/#/calendar');await page.evaluate(()=>HVCalendar.openTripPlanner({start:'2026-12-05',end:'2026-12-12'}));const wizard=page.locator('#tripPlannerDialog');
  await wizard.locator('[data-planner-next]').click();await wizard.locator('[name=tripName]').fill('Complete planner test');await wizard.locator('[name=countryName]').fill('Spain');await wizard.locator('[data-planner-next]').click();await wizard.locator('[data-planner-add-transport]').click();await wizard.locator('[name=type]').selectOption('train');await wizard.locator('[data-planner-flight]').click();assert.equal(await f.locator('[name=type]').inputValue(),'train','Planner uses the shared ground transport editor');
  for(const [side,term]of [['start','Stansted'],['end','Peterborough']]){await f.locator(`[name=${side}name]`).fill(term);await f.locator(`[data-airport-results=${side}] [data-travel-result]`).first().click();}
  await f.locator('[name=startLocal]').fill('2026-12-05T08:00');await f.locator('[name=endLocal]').fill('2026-12-05T10:00');await f.locator('[data-ground-add]').click();await f.locator('[data-via-field=name]').fill('Cambridge');await f.locator('[data-via-results] [data-travel-result]').first().click();
  await f.locator('.transport-extras details summary').click();await moreDetails(f);await f.locator('[name=notes]').fill('Planner transport notes');await f.locator('[name=priceAmount]').fill('45');await f.locator('[name=operator]').fill('Planner Rail');await f.locator('[name=serviceNumber]').fill('P45');await f.locator('[name=addReturn]').check();await f.locator('[type=submit]').click();
  await f.locator('[name=startLocal]').fill('2026-12-12T08:00');await f.locator('[name=endLocal]').fill('2026-12-12T10:00');await f.locator('.transport-extras details summary').click();await f.locator('[name=priceAmount]').fill('50');await f.locator('[name=priceCurrency]').selectOption('EUR');await f.locator('[type=submit]').click();assert.equal(await wizard.locator('[data-planner-transport]').count(),2,'Planner retains both return-linked drafts');
  await wizard.locator('[data-planner-flight]').first().click();const draftId=await page.evaluate(()=>document.getElementById('transportForm')._flightRecord.id);assert.equal(await f.locator('[name=notes]').inputValue(),'Planner transport notes');await moreDetails(f);await f.locator('[name=notes]').fill('Edited planner transport notes');await f.locator('[type=submit]').click();
  await wizard.locator('[data-planner-next]').click();await wizard.locator('[data-planner-add-accommodation]').click();await wizard.locator('[data-planner-place]').click();await p.locator('[name=query]').fill('Peterborough');await p.locator('[data-place-result]').first().click();await p.locator('[data-place-details]>summary').click();await p.locator('[name=placeName]').fill('Planner House Sit');await p.locator('[name=placeType]').selectOption('House Sit');await p.locator('[name=recordNotes]').fill('Keys with neighbour\nSecond line');await p.locator('[name=priceAmount]').fill('75');await p.locator('[name=priceCurrency]').selectOption('USD');await p.locator('[type=submit]').click();
  assert.equal(await wizard.locator('[name=notes]').inputValue(),'Keys with neighbour\nSecond line');assert.equal(await wizard.locator('[name=priceAmount]').inputValue(),'75');assert.equal(await wizard.locator('[name=priceCurrency]').inputValue(),'USD');
  await wizard.locator('[data-planner-back]').click();await wizard.locator('[data-planner-next]').click();await wizard.locator('[data-planner-next]').click();await wizard.locator('[type=submit]').click();await page.waitForFunction(()=>state.trips.some(t=>t.name==='Complete planner test'));
  const planned=await page.evaluate(()=>{const trip=state.trips.find(t=>t.name==='Complete planner test');return{trip,transports:state.transports.filter(t=>t.tripId===trip.id),accommodation:state.accommodations.find(a=>a.tripId===trip.id)};});assert.equal(planned.transports.length,2);assert.equal(planned.transports[0].id,draftId);assert.equal(planned.transports[0].relatedTransportId,planned.transports[1].id);assert.equal(planned.transports[1].relatedTransportId,draftId);assert.equal(planned.transports[0].roundTripId,planned.transports[1].roundTripId);assert.equal(planned.transports[0].notes,'Edited planner transport notes');assert.equal(planned.transports[0].operator,'Planner Rail');assert.equal(planned.transports[0].via.length,1);assert.deepEqual(planned.transports[0].price,{amount:45,currency:'GBP'});assert.deepEqual(planned.transports[1].price,{amount:50,currency:'EUR'});assert.deepEqual(planned.accommodation.price,{amount:75,currency:'USD'});assert.equal(planned.accommodation.type,'House Sit');assert.equal(planned.accommodation.notes,'Keys with neighbour\nSecond line');
  await page.evaluate(()=>{state.accommodations.push({id:'legacy-price-test',profileId:'p',propertyName:'Existing unplotted stay',location:'Madrid',checkIn:'2026-12-05',checkOut:'2026-12-12',notes:'Existing notes'});HVCalendar.openAccommodationDialog(null,'legacy-price-test');});const legacy=page.locator('dialog[aria-label="Edit accommodation"]');await legacy.locator('[name=priceAmount]').fill('120');await legacy.locator('[name=priceCurrency]').selectOption('EUR');await legacy.locator('[type=submit]').click();await page.reload();await page.waitForFunction(()=>window.HVCalendar?.ready);assert.deepEqual(await page.evaluate(()=>state.accommodations.find(a=>a.id==='legacy-price-test').price),{amount:120,currency:'EUR'});assert.equal(await page.evaluate(id=>state.transports.find(t=>t.id===id).notes,draftId),'Edited planner transport notes');
assert.deepEqual(errors,[]);await page.close();
 }
 console.log('Master browser checks passed: live search, precise routes, return links, complete planner drafts, notes/prices, House Sit, legacy stays, trip metadata preservation, photos, repeat-stay maps, hover/branding and refresh at 390/1440px.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
