/* End-to-end brief checks use fictional data and deterministic network responses. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),binary=require('@sparticuz/chromium');binary.setGraphicsMode=false;
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results/master');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)&&p!==root){res.writeHead(403);res.end();return;}if(!path.extname(p))p=path.join(p,'index.html');try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});
const seed={version:2,activeProfileId:'p',profiles:[{id:'p',name:'Fictional traveller',citizenships:['GB'],enabledRules:['schengen']}],trips:[],stays:[],transports:[],accommodations:[],placeVisits:[],residences:[],savedPlaces:[]};
let browser;
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({executablePath:process.env.HV_CHROMIUM_PATH||await binary.executablePath(),args:binary.args.filter(a=>a!=='--single-process'),headless:true});
 for(const width of [390,1440]){let searchRequests=0;
  const page=await browser.newPage({viewport:{width,height:960},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install({time:new Date('2026-10-02T12:00:00Z')});
  await page.route('**/*',r=>{const url=r.request().url();if(url.startsWith(origin))return r.continue();
   if(url.includes('photon.komoot.io/')){searchRequests++;const term=new URL(url).searchParams.get('q')||'',city=term.includes('Peter')?'Peterborough':term.includes('Cambridge')?'Cambridge':'Stansted Airport';const props=(name,type,id)=>({osm_type:'N',osm_id:id,name,osm_value:type,street:'Station Road',city,country:'United Kingdom',countrycode:'gb'});return r.fulfill({json:{features:[{geometry:{coordinates:[-.25,52.5]},properties:props(city,'city',1)},{geometry:{coordinates:[-.24,52.57]},properties:props(city+' railway station','station',city==='Cambridge'?3:city==='Peterborough'?4:2)}]}});}
   return r.abort();
  });
  await page.addInitScript(data=>{if(!localStorage.getItem('whereIveBeen.data.v2'))localStorage.setItem('whereIveBeen.data.v2',JSON.stringify(data));},seed);
  await page.goto(origin+'/#/calendar');await page.waitForFunction(()=>window.HVCalendar?.ready&&window.HVTravelSearch);
  await page.evaluate(()=>HVJourneys.openTransport(null,{type:'train'}));
  const f=page.locator('#transportForm');
  for(const [side,term]of [['start','Stansted'],['end','Peterborough']]){await f.locator(`[name=${side}name]`).fill(term);await f.locator(`[data-airport-results=${side}] [data-travel-result]`).first().click();assert.match(await f.locator(`[name=${side}name]`).inputValue(),/railway station/);}
  await f.locator('[name=startLocal]').fill('2026-10-10T23:30');await f.locator('[name=endLocal]').fill('2026-10-12T06:30');
  await f.locator('[data-ground-add]').click();await f.locator('[data-via-field=name]').fill('Cambridge');await f.locator('[data-via-results] [data-travel-result]').first().click();
  await f.locator('[data-via-field=arrivalLocal]').fill('2026-10-11T09:00');await f.locator('[data-via-field=departureLocal]').fill('2026-10-11T10:00');
  await f.locator('.transport-extras details summary').click();await f.locator('[name=operator]').fill('Fictional Rail');await f.locator('[name=serviceNumber]').fill('R123');await f.locator('[name=notes]').fill('Platform 4\nKeep both tickets');await f.locator('[name=priceAmount]').fill('25.50');
  await f.locator('[name=addReturn]').check();await f.locator('[type=submit]').click();
  assert.equal(await page.evaluate(()=>state.transports.length),0,'Outbound is held until both journeys are valid');assert.match(await f.locator('[name=startname]').inputValue(),/Peterborough/);assert.equal(await f.locator('[name=startLocal]').inputValue(),'','Return times require an independent choice');assert.equal(await f.locator('[name=notes]').inputValue(),'');
  await f.locator('[name=startLocal]').fill('2026-10-20T08:00');await f.locator('[name=endLocal]').fill('2026-10-20T10:00');await f.locator('.transport-extras details summary').click();await f.locator('[name=operator]').fill('Different Rail');await f.locator('[name=priceAmount]').fill('30');await f.locator('[name=priceCurrency]').selectOption('EUR');await f.locator('[type=submit]').click();
  const records=await page.evaluate(()=>state.transports);assert.equal(records.length,2);assert.equal(records[0].via[0].name,'Cambridge railway station');assert.equal(records[0].start.address,'Station Road, Stansted Airport, United Kingdom');assert.equal(records[0].notes,'Platform 4\nKeep both tickets');assert.deepEqual(records[0].price,{amount:25.5,currency:'GBP'});assert.equal(records[0].relatedTransportId,records[1].id);assert.equal(records[1].operator,'Different Rail');assert.deepEqual(records[1].price,{amount:30,currency:'EUR'});
  for(const date of ['2026-10-10','2026-10-11','2026-10-12'])assert.ok(await page.locator(`[data-calendar-date="${date}"] .calendar-day-transport`).count(),'Multi-day journey on '+date);
  await page.evaluate(()=>HVPlaces.open({accommodation:true,place:{id:'test-hotel',name:'Fictional House Sit',lat:52,lon:0,countryCode:'GB',countryName:'United Kingdom',address:'10 Test Lane'},date:'2026-10-10',end:'2026-10-12'}));
  const p=page.locator('.place-search-dialog');assert.equal(await p.locator('[name=code]').count(),0);await p.locator('[name=placeType]').selectOption('House Sit');await p.locator('[name=recordNotes]').fill('Keys with neighbour\nFeed the cat');await p.locator('[name=priceAmount]').fill('0');await p.locator('[type=submit]').click();
  assert.equal(await page.evaluate(()=>state.accommodations[0].type),'House Sit');await page.reload();await page.waitForFunction(()=>window.HVCalendar?.ready);assert.equal(await page.evaluate(()=>state.transports.length),2);assert.equal(await page.evaluate(()=>state.accommodations[0].notes),'Keys with neighbour\nFeed the cat');
  await page.evaluate(()=>state.transports.push({...state.transports[0],id:'excluded-transfer',price:{amount:300,currency:'GBP'}}));
  await page.locator('.day-number[data-calendar-date-select="2026-10-10"]').click();await page.locator('.day-number[data-calendar-date-select="2026-10-12"]').click();await page.locator('[data-create-range-trip]').click();
  const trip=page.locator('dialog[aria-label="Create trip"]');await trip.locator('[name=name]').fill('Fictional railway trip');await trip.locator('[name=notes]').fill('Trip notes\nSecond line');await trip.locator('[data-record-id=excluded-transfer]').uncheck();await trip.locator('[type=submit]').click();
  assert.equal(await page.evaluate(()=>state.trips.length),1);assert.equal(await page.evaluate(()=>state.transports.length),3);assert.equal(await page.evaluate(()=>state.accommodations.length),1);assert.ok(await page.evaluate(()=>!HVCalendar.journeyGroups().find(g=>g.trip?.id===state.trips[0].id).transports.some(t=>t.id==='excluded-transfer')),'Explicit exclusions are not inferred back into the trip');assert.ok(await page.evaluate(()=>state.transports[0].tripId===state.trips[0].id));assert.equal(await page.evaluate(()=>state.transports[1].tripId),null,'Return outside the date range stays standalone');
  const detail=page.locator('dialog[aria-label="Trip details"]');assert.match(await detail.innerText(),/£25.50/);await detail.locator('[data-trip-photos]').setInputFiles(path.join(root,'assets/herald-favicon.png'));await detail.locator('.trip-gallery img').waitFor({timeout:10000});assert.equal(await page.evaluate(()=>state.trips[0].photos.length),1);await detail.locator('[data-close]').click();await page.reload();await page.waitForFunction(()=>window.HVCalendar?.ready);assert.equal(await page.evaluate(()=>state.trips[0].photos.length),1);assert.equal(await page.evaluate(()=>state.trips[0].notes),'Trip notes\nSecond line');
  const cell=page.locator('[data-calendar-date="2026-10-10"]').first();await cell.scrollIntoViewIfNeeded();await page.waitForTimeout(100);const box=await cell.boundingBox();await cell.locator('.calendar-day-transport').first().hover();await page.locator('#calendarFloatingDetail').waitFor();assert.match(await page.locator('#calendarFloatingDetail').innerText(),/Fictional Rail/);assert.deepEqual(await cell.boundingBox(),box,'Hover details never move the cell');
  await page.mouse.move(0,0);await page.goto(origin+'/#/dashboard');await page.locator('.brand').click();assert.match(page.url(),/#\/dashboard$/);
  for(const theme of ['light','dark']){await page.evaluate(t=>{document.documentElement.dataset.theme=t;window.dispatchEvent(new Event('themechange'));},theme);assert.equal(await page.locator('.brand-logo-mark').evaluate(img=>img.naturalWidth),2048);}
  await page.evaluate(()=>HVJourneys.openTransport(null,{type:'train'}));const beforeSearch=searchRequests;await page.locator('#transportForm [name=startname]').fill('Peterborough Last');await page.locator('#transportForm [data-travel-result]').first().waitFor();assert.equal(searchRequests-beforeSearch,2,'Reopening forms does not accumulate duplicate live-search handlers');assert.equal(await page.locator('#transportForm [name=priceCurrency]').inputValue(),'GBP');await page.locator('[data-close-transport]').first().click();
  await page.goto(origin+'/#/calendar');await page.waitForFunction(()=>window.HVCalendar?.ready);
  await page.screenshot({path:path.join(out,'transport-calendar-'+width+'.png'),fullPage:true});
  await page.evaluate(()=>{const host=document.createElement('div');host.id='icon-check';host.innerHTML=['flight','boat','bus','car','train','walk','other'].map(t=>HVTransportIcons.html(t)).join('');document.body.append(host);});await page.waitForFunction(()=>[...document.querySelectorAll('#icon-check img')].every(i=>i.complete&&i.naturalWidth));const sizes=await page.locator('#icon-check img').evaluateAll(images=>images.map(i=>({height:i.getBoundingClientRect().height,ratio:i.getBoundingClientRect().width/i.getBoundingClientRect().height,natural:i.naturalWidth/i.naturalHeight})));assert.equal(new Set(sizes.map(i=>i.height)).size,1);for(const i of sizes)assert.ok(Math.abs(i.ratio-i.natural)<.01,'Supplied icon aspect ratio preserved');await page.locator('#icon-check').evaluate(el=>el.remove());
  await page.evaluate(()=>{const a=state.accommodations[0];state.accommodations.push({...a,id:'repeat',tripId:null,checkIn:'2026-11-01',checkOut:'2026-11-02'},{...a,id:'neighbour',tripId:null,propertyName:'Separate neighbouring hotel',placeId:'another-place',place:{...a.place,id:'another-place',name:'Separate neighbouring hotel'},checkIn:'2026-11-01',checkOut:'2026-11-02'});});await page.evaluate(()=>location.hash='/journey-map');await page.waitForSelector('.marker-accommodation');assert.equal(await page.locator('.journey-cluster').count(),0);assert.equal(await page.locator('.marker-accommodation').count(),2,'Only exact-property repeat stays share a marker');assert.equal(await page.locator('.marker-accommodation small').innerText(),'×2');assert.equal(await page.locator('.marker-accommodation').first().evaluate(e=>e.getBoundingClientRect().width),16);
assert.deepEqual(errors,[]);await page.close();
 }
 console.log('Master browser checks passed: live station search, addresses, vias, independent returns, notes, prices, House Sit, date-range Trips, original-cost totals, photos, hover stability, branding, multi-day Calendar and refresh at 390/1440px.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
