const {test}=require('node:test'),assert=require('node:assert/strict'),J=require('../journey-model.js'),C=require('../calendar-layout-model.js'),P=require('../saved-places-model.js'),M=require('../account-model.js'),G=require('../journey-global-model.js');
const base=()=>({activeProfileId:'a',profiles:[{id:'a',homeCountryCodes:['DE']}],stays:[],trips:[],residences:[],transports:[],accommodations:[],placeVisits:[]});
test('Domestic trips in any country count days and memories, ordinary home stays do not; count home once',()=>{const s=base();s.stays=[{id:'holiday',countryCode:'DE',countryName:'Germany',start:'2000-09-29',end:'2000-09-30',travelKind:'trip'},{id:'home',countryCode:'DE',start:'1990-01-01',end:'2026-10-01',travelKind:'home'}];const before=JSON.stringify(s),summary=J.summary(s,'2026-09-29');assert.equal(summary.days.size,2);assert.equal(summary.trips.size,1);assert.deepEqual([...summary.countries],['DE']);assert.equal(J.memories(s,'2026-09-29').length,1);assert.equal(J.memories(s,'2026-09-29')[0].year,2000);assert.equal(G.rows(s).filter(r=>r.domestic).length,1);assert.equal(JSON.stringify(s),before);});
test('Home evidence is derived conservatively; explicit home overrides trip links and ambiguity stays unchanged',()=>{const s=base(),a={id:'s',countryCode:'DE',start:'2026-01-01',end:'2026-01-03'};assert.equal(J.homeKind(s,a),'ambiguous');s.trips=[{id:'t'}];a.tripId='t';assert.equal(J.homeKind(s,a),'trip');a.travelKind='home';s.stays=[a];const stay={id:'hotel',tripId:'t',profileId:'a',checkIn:'2026-01-01',checkOut:'2026-01-03'};assert.equal(J.hiddenHomeRecord(s,stay),true);assert.equal(J.homeKind(s,{...a,travelKind:'trip'}),'trip');});
test('Frequency counts unique foreign dates and years, ties and leap day without domestic or future days',()=>{const s=base();s.stays=[{countryCode:'FR',start:'2020-02-29',end:'2020-02-29'},{countryCode:'BE',start:'2020-02-29',end:'2020-02-29'},{countryCode:'FR',start:'2024-02-29',end:'2024-02-29'},{countryCode:'DE',start:'2020-01-01',end:'2025-12-31',travelKind:'trip'},{countryCode:'FR',start:'2027-02-28',end:'2027-02-28',status:'planned'}];const f=J.travelFrequency(s,'2026-09-29');assert.equal(f.days,2);assert.deepEqual(f.dates,['02-29']);assert.equal(f.yearMax,2);assert.deepEqual(f.weekdays,[4,6]);});
test('Three accommodations align by local journey order, preserve missing times and support proportional times',()=>{const list=[{id:'a',checkIn:'2026-01-01',checkOut:'2026-01-02'},{id:'b',checkIn:'2026-01-02',checkOut:'2026-01-02'},{id:'c',checkIn:'2026-01-02',checkOut:'2026-01-03'}];const before=JSON.stringify(list);assert.deepEqual(C.lodging(list,'2026-01-02').map(x=>x.width),[1/3,1/3,1/3]);assert.equal(JSON.stringify(list),before);const timed=C.lodging([{...list[0],checkOutTime:'06:00',timeZone:'Europe/London'},{...list[2],checkInTime:'06:00',timeZone:'Europe/London'}],'2026-01-02');assert.deepEqual(timed.map(x=>x.width),[.25,.75]);});
test('Private saved places deduplicate by name, address and coordinates and survive import without modifying snapshots',()=>{const rows=[],place={name:'El Dorado Inn',address:'Test Road',countryCode:'GY',lat:6.8,lon:-58.15};const a=P.upsert(rows,place,'a'),b=P.upsert(rows,{...place,name:'EL DORADO INN'},'a');assert.equal(a.id,b.id);assert.equal(rows.length,1);assert.equal(P.search(rows,'el dorado','a').length,1);assert.equal(P.search(rows,'EL DOR','b').length,0);const snapshot=JSON.stringify(place);a.place.name='New name';assert.equal(JSON.stringify(place),snapshot);a.deleted=true;assert.equal(P.search(rows,'new','a').length,0);const imported=M.importData({profiles:[{id:'a'}]},{profiles:[{id:'a'}],savedPlaces:rows,visaAcknowledgements:[{id:'notice',profileId:'a',fingerprint:'v1'}]}).data;assert.deepEqual(imported.savedPlaces,rows);assert.deepEqual(M.importData(imported,{savedPlaces:rows}).data.savedPlaces,rows);});
test('Renamed or removed saved places are not recreated from old snapshots',()=>{const rows=[],p={id:'manual:inn',name:'Old Inn',lat:1,lon:2},r=P.upsert(rows,p,'a');r.place.name='Updated Inn';assert.equal(P.upsert(rows,p,'a').id,r.id);r.deleted=true;P.upsert(rows,p,'a');assert.equal(rows.length,1);assert.equal(P.search(rows,'Inn','a').length,0);});
test('Explicit domestic and foreign plotted trips win over a broad ordinary-home period',()=>{const s=base();s.stays=[{id:'home',countryCode:'DE',start:'2020-01-01',end:'2030-01-01',travelKind:'home'}];assert.equal(J.hiddenHomeRecord(s,{travelKind:'trip',checkIn:'2026-01-01',checkOut:'2026-01-02',place:{countryCode:'DE'}}),false);assert.equal(J.hiddenHomeRecord(s,{checkIn:'2026-01-01',checkOut:'2026-01-02',place:{countryCode:'ES'}}),false);assert.equal(J.dayStatus({...s,accommodations:[{travelKind:'trip',checkIn:'2026-01-01',checkOut:'2026-01-02',place:{countryCode:'DE'}}]},'2026-01-01'),'mixed');});
test('Airport details enrich old code-only endpoints without changing their snapshots',()=>{const p={name:'ALC',iata:'ALC'},before=JSON.stringify(p);assert.equal(J.airportDetails(p,()=>({name:'Alicante-Elche Airport',city:'Alicante',countryCodes:['ES'],icao:'LEAL'})),'Alicante-Elche Airport, Alicante, Spain (ALC / LEAL)');assert.equal(JSON.stringify(p),before);});
test('Travel frequency includes recorded foreign residences and uses configured sovereign home',()=>{const s=base();s.residences=[{countryCode:'FR',start:'2001-09-29',end:'2001-09-29'}];assert.equal(J.travelFrequency(s,'2026-09-29').days,1);});
test('Saved-place and visa records merge across devices; visa references follow imported profiles and stays',()=>{const remote={profiles:[{id:'a',name:'Me'}],stays:[{id:'s',profileId:'a',countryCode:'FR'}],savedPlaces:[],visaAcknowledgements:[]},source={profiles:[{id:'b',name:'Me'}],stays:[{id:'other',profileId:'b',countryCode:'FR'}],visaAcknowledgements:[{id:'notice',profileId:'b',stayId:'other'}]};const imported=M.importData(remote,source).data;assert.equal(imported.visaAcknowledgements[0].profileId,'a');assert.equal(imported.visaAcknowledgements[0].stayId,'s');const base={savedPlaces:[{id:'place',place:{name:'Inn',lat:1,lon:2}}]},local=M.copy(base),cloud=M.copy(base);local.savedPlaces[0].place.name='New Inn';cloud.savedPlaces[0].place.address='Road';const merged=M.merge(base,local,cloud);assert.equal(merged.conflicts.length,0);assert.equal(merged.data.savedPlaces[0].place.name,'New Inn');assert.equal(merged.data.savedPlaces[0].place.address,'Road');});
test('Date-line accommodation preserves entered journey order when local zones differ',()=>{const stays=[{id:'tokyo',checkIn:'2026-09-13',checkOut:'2026-09-14',checkInTime:'14:00',timeZone:'Asia/Tokyo'},{id:'honolulu',checkIn:'2026-09-12',checkOut:'2026-09-13',checkOutTime:'11:00',timeZone:'Pacific/Honolulu'}];assert.deepEqual(C.lodging(stays,'2026-09-13').map(x=>[x.record.id,x.width]),[['tokyo',.5],['honolulu',.5]]);});

test('Long home-country residence periods never become memories through transport evidence',()=>{const s=base();s.residences=[{id:'home-period',profileId:'a',countryCode:'DE',countryName:'Germany',start:'1990-01-01',end:'2020-12-31'}];s.transports=[{id:'departure',profileId:'a',type:'flight',start:{countryCode:'DE'},end:{countryCode:'FR'},startLocal:'2010-09-29T08:00',endLocal:'2010-09-29T10:00'}];assert.deepEqual(J.memories(s,'2026-09-29'),[]);s.stays.push({id:'holiday',profileId:'a',countryCode:'DE',countryName:'Germany',start:'2005-09-29',end:'2005-09-29',travelKind:'trip'});assert.deepEqual(J.memories(s,'2026-09-29').map(m=>m.year),[2005]);});
