const COUNTRIES = [
  { 'code': 'SEA', 'name': 'At Sea' },
  { 'code': 'AF', 'name': 'Afghanistan' },
  { 'code': 'AL', 'name': 'Albania' },
  { 'code': 'DZ', 'name': 'Algeria' },
  { 'code': 'AS', 'name': 'American Samoa' },
  { 'code': 'AD', 'name': 'Andorra' },
  { 'code': 'AO', 'name': 'Angola' },
  { 'code': 'AI', 'name': 'Anguilla' },
  { 'code': 'AQ', 'name': 'Antarctica' },
  { 'code': 'AG', 'name': 'Antigua and Barbuda' },
  { 'code': 'AR', 'name': 'Argentina' },
  { 'code': 'AM', 'name': 'Armenia' },
  { 'code': 'AW', 'name': 'Aruba' },
  { 'code': 'AU', 'name': 'Australia' },
  { 'code': 'AT', 'name': 'Austria' },
  { 'code': 'AZ', 'name': 'Azerbaijan' },
  { 'code': 'BS', 'name': 'Bahamas' },
  { 'code': 'BH', 'name': 'Bahrain' },
  { 'code': 'BD', 'name': 'Bangladesh' },
  { 'code': 'BB', 'name': 'Barbados' },
  { 'code': 'BY', 'name': 'Belarus' },
  { 'code': 'BE', 'name': 'Belgium' },
  { 'code': 'BZ', 'name': 'Belize' },
  { 'code': 'BJ', 'name': 'Benin' },
  { 'code': 'BM', 'name': 'Bermuda' },
  { 'code': 'BT', 'name': 'Bhutan' },
  { 'code': 'BO', 'name': 'Bolivia' },
  { 'code': 'BQ', 'name': 'Bonaire, Sint Eustatius and Saba' },
  { 'code': 'BA', 'name': 'Bosnia and Herzegovina' },
  { 'code': 'BW', 'name': 'Botswana' },
  { 'code': 'BOU', 'name': 'Bougainville' },
  { 'code': 'BV', 'name': 'Bouvet Island' },
  { 'code': 'BR', 'name': 'Brazil' },
  { 'code': 'IO', 'name': 'British Indian Ocean Territory' },
  { 'code': 'BN', 'name': 'Brunei' },
  { 'code': 'BG', 'name': 'Bulgaria' },
  { 'code': 'BF', 'name': 'Burkina Faso' },
  { 'code': 'BI', 'name': 'Burundi' },
  { 'code': 'CV', 'name': 'Cabo Verde' },
  { 'code': 'KH', 'name': 'Cambodia' },
  { 'code': 'CM', 'name': 'Cameroon' },
  { 'code': 'CA', 'name': 'Canada' },
  { 'code': 'KY', 'name': 'Cayman Islands' },
  { 'code': 'CF', 'name': 'Central African Republic' },
  { 'code': 'TD', 'name': 'Chad' },
  { 'code': 'CL', 'name': 'Chile' },
  { 'code': 'CN', 'name': 'China' },
  { 'code': 'CX', 'name': 'Christmas Island' },
  { 'code': 'CC', 'name': 'Cocos (Keeling) Islands' },
  { 'code': 'CO', 'name': 'Colombia' },
  { 'code': 'KM', 'name': 'Comoros' },
  { 'code': 'CG', 'name': 'Congo' },
  { 'code': 'CK', 'name': 'Cook Islands' },
  { 'code': 'CR', 'name': 'Costa Rica' },
  { 'code': 'HR', 'name': 'Croatia' },
  { 'code': 'CU', 'name': 'Cuba' },
  { 'code': 'CW', 'name': 'Cura\u00e7ao' },
  { 'code': 'CY', 'name': 'Cyprus' },
  { 'code': 'CZ', 'name': 'Czechia' },
  { 'code': 'CI', 'name': "C\u00f4te d'Ivoire" },
  { 'code': 'CD', 'name': 'DR Congo' },
  { 'code': 'DK', 'name': 'Denmark' },
  { 'code': 'DJ', 'name': 'Djibouti' },
  { 'code': 'DM', 'name': 'Dominica' },
  { 'code': 'DO', 'name': 'Dominican Republic' },
  { 'code': 'EC', 'name': 'Ecuador' },
  { 'code': 'EG', 'name': 'Egypt' },
  { 'code': 'SV', 'name': 'El Salvador' },
  { 'code': 'GQ', 'name': 'Equatorial Guinea' },
  { 'code': 'ER', 'name': 'Eritrea' },
  { 'code': 'EE', 'name': 'Estonia' },
  { 'code': 'SZ', 'name': 'Eswatini' },
  { 'code': 'ET', 'name': 'Ethiopia' },
  { 'code': 'FK', 'name': 'Falkland Islands (Malvinas)' },
  { 'code': 'FO', 'name': 'Faroe Islands' },
  { 'code': 'FJ', 'name': 'Fiji' },
  { 'code': 'FI', 'name': 'Finland' },
  { 'code': 'FR', 'name': 'France' },
  { 'code': 'GF', 'name': 'French Guiana' },
  { 'code': 'PF', 'name': 'French Polynesia' },
  { 'code': 'TF', 'name': 'French Southern Territories' },
  { 'code': 'GA', 'name': 'Gabon' },
  { 'code': 'GM', 'name': 'Gambia' },
  { 'code': 'GE', 'name': 'Georgia' },
  { 'code': 'DE', 'name': 'Germany' },
  { 'code': 'GH', 'name': 'Ghana' },
  { 'code': 'GI', 'name': 'Gibraltar' },
  { 'code': 'GR', 'name': 'Greece' },
  { 'code': 'GL', 'name': 'Greenland' },
  { 'code': 'GD', 'name': 'Grenada' },
  { 'code': 'GP', 'name': 'Guadeloupe' },
  { 'code': 'GU', 'name': 'Guam' },
  { 'code': 'GT', 'name': 'Guatemala' },
  { 'code': 'GG', 'name': 'Guernsey' },
  { 'code': 'GN', 'name': 'Guinea' },
  { 'code': 'GW', 'name': 'Guinea-Bissau' },
  { 'code': 'GY', 'name': 'Guyana' },
  { 'code': 'HT', 'name': 'Haiti' },
  { 'code': 'HM', 'name': 'Heard Island and McDonald Islands' },
  { 'code': 'VA', 'name': 'Holy See (Vatican City State)' },
  { 'code': 'HN', 'name': 'Honduras' },
  { 'code': 'HK', 'name': 'Hong Kong' },
  { 'code': 'HU', 'name': 'Hungary' },
  { 'code': 'IS', 'name': 'Iceland' },
  { 'code': 'IN', 'name': 'India' },
  { 'code': 'ID', 'name': 'Indonesia' },
  { 'code': 'IR', 'name': 'Iran' },
  { 'code': 'IQ', 'name': 'Iraq' },
  { 'code': 'IE', 'name': 'Ireland' },
  { 'code': 'IM', 'name': 'Isle of Man' },
  { 'code': 'IL', 'name': 'Israel' },
  { 'code': 'IT', 'name': 'Italy' },
  { 'code': 'JM', 'name': 'Jamaica' },
  { 'code': 'JP', 'name': 'Japan' },
  { 'code': 'JE', 'name': 'Jersey' },
  { 'code': 'JO', 'name': 'Jordan' },
  { 'code': 'KZ', 'name': 'Kazakhstan' },
  { 'code': 'KE', 'name': 'Kenya' },
  { 'code': 'KI', 'name': 'Kiribati' },
  { 'code': 'XK', 'name': 'Kosovo' },
  { 'code': 'KW', 'name': 'Kuwait' },
  { 'code': 'KG', 'name': 'Kyrgyzstan' },
  { 'code': 'LA', 'name': 'Laos' },
  { 'code': 'LV', 'name': 'Latvia' },
  { 'code': 'LB', 'name': 'Lebanon' },
  { 'code': 'LS', 'name': 'Lesotho' },
  { 'code': 'LR', 'name': 'Liberia' },
  { 'code': 'LY', 'name': 'Libya' },
  { 'code': 'LI', 'name': 'Liechtenstein' },
  { 'code': 'LT', 'name': 'Lithuania' },
  { 'code': 'LU', 'name': 'Luxembourg' },
  { 'code': 'MO', 'name': 'Macao' },
  { 'code': 'MG', 'name': 'Madagascar' },
  { 'code': 'MW', 'name': 'Malawi' },
  { 'code': 'MY', 'name': 'Malaysia' },
  { 'code': 'MV', 'name': 'Maldives' },
  { 'code': 'ML', 'name': 'Mali' },
  { 'code': 'MT', 'name': 'Malta' },
  { 'code': 'MH', 'name': 'Marshall Islands' },
  { 'code': 'MQ', 'name': 'Martinique' },
  { 'code': 'MR', 'name': 'Mauritania' },
  { 'code': 'MU', 'name': 'Mauritius' },
  { 'code': 'YT', 'name': 'Mayotte' },
  { 'code': 'MX', 'name': 'Mexico' },
  { 'code': 'FM', 'name': 'Micronesia, Federated States of' },
  { 'code': 'MD', 'name': 'Moldova' },
  { 'code': 'MC', 'name': 'Monaco' },
  { 'code': 'MN', 'name': 'Mongolia' },
  { 'code': 'ME', 'name': 'Montenegro' },
  { 'code': 'MS', 'name': 'Montserrat' },
  { 'code': 'MA', 'name': 'Morocco' },
  { 'code': 'MZ', 'name': 'Mozambique' },
  { 'code': 'MM', 'name': 'Myanmar' },
  { 'code': 'NA', 'name': 'Namibia' },
  { 'code': 'NR', 'name': 'Nauru' },
  { 'code': 'NP', 'name': 'Nepal' },
  { 'code': 'NL', 'name': 'Netherlands' },
  { 'code': 'NC', 'name': 'New Caledonia' },
  { 'code': 'NZ', 'name': 'New Zealand' },
  { 'code': 'NI', 'name': 'Nicaragua' },
  { 'code': 'NE', 'name': 'Niger' },
  { 'code': 'NG', 'name': 'Nigeria' },
  { 'code': 'NU', 'name': 'Niue' },
  { 'code': 'NF', 'name': 'Norfolk Island' },
  { 'code': 'KP', 'name': 'North Korea' },
  { 'code': 'MK', 'name': 'North Macedonia' },
  { 'code': 'MP', 'name': 'Northern Mariana Islands' },
  { 'code': 'NO', 'name': 'Norway' },
  { 'code': 'OM', 'name': 'Oman' },
  { 'code': 'PK', 'name': 'Pakistan' },
  { 'code': 'PW', 'name': 'Palau' },
  { 'code': 'PS', 'name': 'Palestine' },
  { 'code': 'PA', 'name': 'Panama' },
  { 'code': 'PG', 'name': 'Papua New Guinea' },
  { 'code': 'PY', 'name': 'Paraguay' },
  { 'code': 'PE', 'name': 'Peru' },
  { 'code': 'PH', 'name': 'Philippines' },
  { 'code': 'PN', 'name': 'Pitcairn' },
  { 'code': 'PL', 'name': 'Poland' },
  { 'code': 'PT', 'name': 'Portugal' },
  { 'code': 'PR', 'name': 'Puerto Rico' },
  { 'code': 'QA', 'name': 'Qatar' },
  { 'code': 'RO', 'name': 'Romania' },
  { 'code': 'RU', 'name': 'Russia' },
  { 'code': 'RW', 'name': 'Rwanda' },
  { 'code': 'RE', 'name': 'R\u00e9union' },
  { 'code': 'BL', 'name': 'Saint Barth\u00e9lemy' },
  { 'code': 'SH', 'name': 'Saint Helena, Ascension and Tristan da Cunha' },
  { 'code': 'KN', 'name': 'Saint Kitts and Nevis' },
  { 'code': 'LC', 'name': 'Saint Lucia' },
  { 'code': 'MF', 'name': 'Saint Martin (French part)' },
  { 'code': 'PM', 'name': 'Saint Pierre and Miquelon' },
  { 'code': 'VC', 'name': 'Saint Vincent and the Grenadines' },
  { 'code': 'WS', 'name': 'Samoa' },
  { 'code': 'SM', 'name': 'San Marino' },
  { 'code': 'ST', 'name': 'Sao Tome and Principe' },
  { 'code': 'SA', 'name': 'Saudi Arabia' },
  { 'code': 'SN', 'name': 'Senegal' },
  { 'code': 'RS', 'name': 'Serbia' },
  { 'code': 'SC', 'name': 'Seychelles' },
  { 'code': 'SL', 'name': 'Sierra Leone' },
  { 'code': 'SG', 'name': 'Singapore' },
  { 'code': 'SX', 'name': 'Sint Maarten (Dutch part)' },
  { 'code': 'SK', 'name': 'Slovakia' },
  { 'code': 'SI', 'name': 'Slovenia' },
  { 'code': 'SB', 'name': 'Solomon Islands' },
  { 'code': 'SO', 'name': 'Somalia' },
  { 'code': 'ZA', 'name': 'South Africa' },
  { 'code': 'GS', 'name': 'South Georgia and the South Sandwich Islands' },
  { 'code': 'KR', 'name': 'South Korea' },
  { 'code': 'SS', 'name': 'South Sudan' },
  { 'code': 'ES', 'name': 'Spain' },
  { 'code': 'LK', 'name': 'Sri Lanka' },
  { 'code': 'SD', 'name': 'Sudan' },
  { 'code': 'SR', 'name': 'Suriname' },
  { 'code': 'SJ', 'name': 'Svalbard and Jan Mayen' },
  { 'code': 'SE', 'name': 'Sweden' },
  { 'code': 'CH', 'name': 'Switzerland' },
  { 'code': 'SY', 'name': 'Syria' },
  { 'code': 'TW', 'name': 'Taiwan' },
  { 'code': 'TJ', 'name': 'Tajikistan' },
  { 'code': 'TZ', 'name': 'Tanzania' },
  { 'code': 'TH', 'name': 'Thailand' },
  { 'code': 'TL', 'name': 'Timor-Leste' },
  { 'code': 'TG', 'name': 'Togo' },
  { 'code': 'TK', 'name': 'Tokelau' },
  { 'code': 'TO', 'name': 'Tonga' },
  { 'code': 'TT', 'name': 'Trinidad and Tobago' },
  { 'code': 'TN', 'name': 'Tunisia' },
  { 'code': 'TM', 'name': 'Turkmenistan' },
  { 'code': 'TC', 'name': 'Turks and Caicos Islands' },
  { 'code': 'TV', 'name': 'Tuvalu' },
  { 'code': 'TR', 'name': 'T\u00fcrkiye' },
  { 'code': 'UG', 'name': 'Uganda' },
  { 'code': 'UA', 'name': 'Ukraine' },
  { 'code': 'AE', 'name': 'United Arab Emirates' },
  { 'code': 'GB', 'name': 'United Kingdom' },
  { 'code': 'US', 'name': 'United States' },
  { 'code': 'UM', 'name': 'United States Minor Outlying Islands' },
  { 'code': 'UY', 'name': 'Uruguay' },
  { 'code': 'UZ', 'name': 'Uzbekistan' },
  { 'code': 'VU', 'name': 'Vanuatu' },
  { 'code': 'VE', 'name': 'Venezuela' },
  { 'code': 'VN', 'name': 'Vietnam' },
  { 'code': 'VG', 'name': 'Virgin Islands, British' },
  { 'code': 'VI', 'name': 'Virgin Islands, U.S.' },
  { 'code': 'WF', 'name': 'Wallis and Futuna' },
  { 'code': 'EH', 'name': 'Western Sahara' },
  { 'code': 'YE', 'name': 'Yemen' },
  { 'code': 'ZM', 'name': 'Zambia' },
  { 'code': 'ZW', 'name': 'Zimbabwe' },
  { 'code': 'AX', 'name': '\u00c5land Islands' },
];
const NUMERIC_TO_ALPHA2 = {
  '533': 'AW',
  '004': 'AF',
  '024': 'AO',
  '660': 'AI',
  '248': 'AX',
  '008': 'AL',
  '020': 'AD',
  '784': 'AE',
  '032': 'AR',
  '051': 'AM',
  '016': 'AS',
  '010': 'AQ',
  '260': 'TF',
  '028': 'AG',
  '036': 'AU',
  '040': 'AT',
  '031': 'AZ',
  '108': 'BI',
  '056': 'BE',
  '204': 'BJ',
  '535': 'BQ',
  '854': 'BF',
  '050': 'BD',
  '100': 'BG',
  '048': 'BH',
  '044': 'BS',
  '070': 'BA',
  '652': 'BL',
  '112': 'BY',
  '084': 'BZ',
  '060': 'BM',
  '068': 'BO',
  '076': 'BR',
  '052': 'BB',
  '096': 'BN',
  '064': 'BT',
  '074': 'BV',
  '072': 'BW',
  '140': 'CF',
  '124': 'CA',
  '166': 'CC',
  '756': 'CH',
  '152': 'CL',
  '156': 'CN',
  '384': 'CI',
  '120': 'CM',
  '180': 'CD',
  '178': 'CG',
  '184': 'CK',
  '170': 'CO',
  '174': 'KM',
  '132': 'CV',
  '188': 'CR',
  '192': 'CU',
  '531': 'CW',
  '162': 'CX',
  '136': 'KY',
  '196': 'CY',
  '203': 'CZ',
  '276': 'DE',
  '262': 'DJ',
  '212': 'DM',
  '208': 'DK',
  '214': 'DO',
  '012': 'DZ',
  '218': 'EC',
  '818': 'EG',
  '232': 'ER',
  '732': 'EH',
  '724': 'ES',
  '233': 'EE',
  '231': 'ET',
  '246': 'FI',
  '242': 'FJ',
  '238': 'FK',
  '250': 'FR',
  '234': 'FO',
  '583': 'FM',
  '266': 'GA',
  '826': 'GB',
  '268': 'GE',
  '831': 'GG',
  '288': 'GH',
  '292': 'GI',
  '324': 'GN',
  '312': 'GP',
  '270': 'GM',
  '624': 'GW',
  '226': 'GQ',
  '300': 'GR',
  '308': 'GD',
  '304': 'GL',
  '320': 'GT',
  '254': 'GF',
  '316': 'GU',
  '328': 'GY',
  '344': 'HK',
  '334': 'HM',
  '340': 'HN',
  '191': 'HR',
  '332': 'HT',
  '348': 'HU',
  '360': 'ID',
  '833': 'IM',
  '356': 'IN',
  '086': 'IO',
  '372': 'IE',
  '364': 'IR',
  '368': 'IQ',
  '352': 'IS',
  '376': 'IL',
  '380': 'IT',
  '388': 'JM',
  '832': 'JE',
  '400': 'JO',
  '392': 'JP',
  '398': 'KZ',
  '404': 'KE',
  '417': 'KG',
  '116': 'KH',
  '296': 'KI',
  '659': 'KN',
  '410': 'KR',
  '414': 'KW',
  '418': 'LA',
  '422': 'LB',
  '430': 'LR',
  '434': 'LY',
  '662': 'LC',
  '438': 'LI',
  '144': 'LK',
  '426': 'LS',
  '440': 'LT',
  '442': 'LU',
  '428': 'LV',
  '446': 'MO',
  '663': 'MF',
  '504': 'MA',
  '492': 'MC',
  '498': 'MD',
  '450': 'MG',
  '462': 'MV',
  '484': 'MX',
  '584': 'MH',
  '807': 'MK',
  '466': 'ML',
  '470': 'MT',
  '104': 'MM',
  '499': 'ME',
  '496': 'MN',
  '580': 'MP',
  '508': 'MZ',
  '478': 'MR',
  '500': 'MS',
  '474': 'MQ',
  '480': 'MU',
  '454': 'MW',
  '458': 'MY',
  '175': 'YT',
  '516': 'NA',
  '540': 'NC',
  '562': 'NE',
  '574': 'NF',
  '566': 'NG',
  '558': 'NI',
  '570': 'NU',
  '528': 'NL',
  '578': 'NO',
  '524': 'NP',
  '520': 'NR',
  '554': 'NZ',
  '512': 'OM',
  '586': 'PK',
  '591': 'PA',
  '612': 'PN',
  '604': 'PE',
  '608': 'PH',
  '585': 'PW',
  '598': 'PG',
  '616': 'PL',
  '630': 'PR',
  '408': 'KP',
  '620': 'PT',
  '600': 'PY',
  '275': 'PS',
  '258': 'PF',
  '634': 'QA',
  '638': 'RE',
  '642': 'RO',
  '643': 'RU',
  '646': 'RW',
  '682': 'SA',
  '729': 'SD',
  '686': 'SN',
  '702': 'SG',
  '239': 'GS',
  '654': 'SH',
  '744': 'SJ',
  '090': 'SB',
  '694': 'SL',
  '222': 'SV',
  '674': 'SM',
  '706': 'SO',
  '666': 'PM',
  '688': 'RS',
  '728': 'SS',
  '678': 'ST',
  '740': 'SR',
  '703': 'SK',
  '705': 'SI',
  '752': 'SE',
  '748': 'SZ',
  '534': 'SX',
  '690': 'SC',
  '760': 'SY',
  '796': 'TC',
  '148': 'TD',
  '768': 'TG',
  '764': 'TH',
  '762': 'TJ',
  '772': 'TK',
  '795': 'TM',
  '626': 'TL',
  '776': 'TO',
  '780': 'TT',
  '788': 'TN',
  '792': 'TR',
  '798': 'TV',
  '158': 'TW',
  '834': 'TZ',
  '800': 'UG',
  '804': 'UA',
  '581': 'UM',
  '858': 'UY',
  '840': 'US',
  '860': 'UZ',
  '336': 'VA',
  '670': 'VC',
  '862': 'VE',
  '092': 'VG',
  '850': 'VI',
  '704': 'VN',
  '548': 'VU',
  '876': 'WF',
  '882': 'WS',
  '887': 'YE',
  '710': 'ZA',
  '894': 'ZM',
  '716': 'ZW',
  '383': 'XK',
};
const SCHENGEN = new Set([
  'AT',
  'BE',
  'BG',
  'HR',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GR',
  'HU',
  'IS',
  'IT',
  'LV',
  'LI',
  'LT',
  'LU',
  'MT',
  'NL',
  'NO',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE',
  'CH',
]);
const EU_EEA_CH = new Set([
  'AT',
  'BE',
  'BG',
  'HR',
  'CY',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GR',
  'HU',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MT',
  'NL',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE',
  'IS',
  'LI',
  'NO',
  'CH',
]);
const APP_KEY = 'whereIveBeen.data.v2',
  LEGACY_KEY = 'whereIveBeen.stays.v1',
  CLOUD_KEY = 'whereIveBeen.cloud.v1',
  LOCAL_SAVED_KEY = 'whereIveBeen.lastSaved.v1';

// DEVICE TRANSFER SERVICE
// Paste the SAME Supabase project URL and PUBLISHABLE key here after running
// device-transfer-setup.sql in that project. These values are safe to expose
// in a browser app when you use a publishable/anon key (NEVER a service-role key).
const TRANSFER_SERVICE = {
  supabaseUrl: 'https://dvbgjdghjjydajmulbjn.supabase.co',
  supabaseKey: 'sb_publishable_TFLW7eFitT9Mw8jML_rzXQ_B43Tgg0H',
  expiresMinutes: 60,
};
const RULES = [
  {
    id: 'schengen',
    name: 'Schengen Area',
    countries: [...SCHENGEN],
    type: 'rolling',
    limit: 90,
    window: 180,
    source:
      'https://home-affairs.ec.europa.eu/policies/schengen/border-crossing/short-stay-calculator_en',
    desc: '90 days in any rolling 180-day period for normal short stays by third-country nationals.',
  },
  {
    id: 'uk',
    name: 'United Kingdom — Standard Visitor',
    countries: ['GB'],
    type: 'months',
    months: 6,
    source: 'https://www.gov.uk/standard-visitor',
    desc: 'A Standard Visitor can usually stay for up to 6 months. Your actual permission and eligibility control.',
  },
  {
    id: 'canada',
    name: 'Canada — visitor',
    countries: ['CA'],
    type: 'months',
    months: 6,
    source: 'https://www.ircc.canada.ca/english/helpcentre/answer.asp?qnum=1016&top=',
    desc: 'Most visitors can stay for up to 6 months, but a border officer may allow a different period.',
  },
  {
    id: 'us-vwp',
    name: 'United States — Visa Waiver Program',
    countries: ['US'],
    type: 'perVisit',
    limit: 90,
    source:
      'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visa-waiver-program.html',
    desc: 'For eligible travellers admitted under the VWP: up to 90 days. Side trips may not reset the original admission period.',
  },
];
