/* Keep readable feature sources and the existing static browser entry points in sync. */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const bundles = require('../src/browser-bundles.json');
const check = process.argv.includes('--check');

for (const bundle of bundles) {
  let body = bundle.files.map(input => {
    if (typeof input === 'object') {
      const data = JSON.parse(fs.readFileSync(path.join(root, input.file), 'utf8'));
      return `// Source: ${input.file}\nconst ${input.constant} = ${JSON.stringify(data)};\n`;
    }
    const file = input;
    const source = fs.readFileSync(path.join(root, file), 'utf8').trimEnd();
    // Each fragment is valid JavaScript; concatenation preserves the original
    // shared scope, declaration hoisting and script order without a module rewrite.
    new vm.Script(source, {filename: file});
    return `// Source: ${file}\n${source}\n`;
  }).join('\n');

  if (bundle.scope === 'closure') {
    // Do not indent the concatenated text: that would change whitespace inside
    // multi-line HTML template literals and could change the rendered interface.
    body = `(() => {\n'use strict';\n\n${body}\n})();\n`;
  } else if (bundle.scope !== 'global') {
    throw new Error(`Unknown browser scope for ${bundle.output}`);
  }

  const output = `/* Generated by scripts/build-browser.cjs. Edit the src/ files listed below. */\n${body}`;
  new vm.Script(output, {filename: bundle.output});
  const target = path.join(root, bundle.output);
  if (check) {
    if (fs.readFileSync(target, 'utf8') !== output) {
      throw new Error(`Run npm run build:browser; ${bundle.output} differs from its sources.`);
    }
  } else {
    fs.writeFileSync(target, output);
  }
}
