"""Create small display variants without changing source artwork or country IDs."""
import json
from pathlib import Path
from PIL import Image
root = Path(__file__).resolve().parents[1]
manifest = json.loads((root / 'assets/flag-manifest.js').read_text().split('=', 1)[1].strip().rstrip(';'))
out = root / 'assets/flags-display'
out.mkdir(exist_ok=True)
paths = {}
for code, source in manifest.items():
    path = root / source
    if path.suffix.lower() != '.png':
        continue
    with Image.open(path) as image:
        image = image.convert('RGBA')
        image.thumbnail((192, 128), Image.Resampling.LANCZOS)
        image.save(out / (code + '.webp'), 'WEBP', lossless=True, method=6)
    paths[code] = 'assets/flags-display/' + code + '.webp'
(root / 'assets/flag-thumbnails.js').write_text('// Generated by scripts/optimise-flags.py; original artwork is retained.\nwindow.HVFlagThumbnails = ' + json.dumps(paths, indent=2) + ';\n')
print(f'Generated {len(paths)} display variants; {sum(p.stat().st_size for p in out.iterdir())} bytes total.')
